### ISSUE TITLE
Trailing slashes

### ISSUE THREAD

**Issue by mmccarty** [intake/filesystem_spec#10]
Should address what to do about trailing `slashes/`.

**Comment by martindurant** [comment]
More detail: does a `/` imply that a path is necessarily a directory? Is it, then, synonymous with the same path without the `/`? (some FSs like S3 don't have directory entries as such, can have both a directory/prefix and file of the same name, and can have regular files ending in `/`)
This arises, for instance, when taking the parent directory of some path.
