### ISSUE TITLE
Attribute error when using hdfs during program exit

### ISSUE THREAD

**Issue by ayushdg** [intake/filesystem_spec#111]
I observe an attribute error when the python program/session ends after using the PyArrowHDFS implementation. This does _not_ impact the program in any way during execution(as far as I have observed).

Reproducer:
```
from fsspec.implementations.hdfs import PyArrowHDFS
fs = PyArrowHDFS()
```
After exit:
```
AttributeError: 'HadoopFileSystem' object has no attribute 'close'
Exception ignored in: 'pyarrow.lib.HadoopFileSystem.__dealloc__'
AttributeError: 'HadoopFileSystem' object has no attribute 'close'
```

**Comment by TomAugspurger** [comment]
Thanks for the report. Is this happening in `PyArrowHDFS.__del__`?

**Comment by ayushdg** [comment]
`PyArrowHDFS` does not seem to have a `__del__`  method (unless I'm missing something)

**Comment by TomAugspurger** [comment]
Does it inherit one? I may be confused.

**Comment by TomAugspurger** [comment]
Sorry, I was confused. I was looking at `AbstractBufferedFile.__del__`.

I can verify the issue with the docker image from https://github.com/dask/dask/tree/master/continuous_integration/hdfs.
