### ISSUE TITLE
Black-ening?

### ISSUE THREAD

**Issue by asford** [intake/filesystem_spec#131]
@martindurant Would you consider adopting [black](https://black.readthedocs.io/en/stable/index.html) as the code format for this repo? I've just noticed in my two recent PRs that the "diff radius" was a bit larger than I'd intended due to accidental code formatting in my editor. Having a pre-established code format may be useful if more folks begin joining this project.

I would be happy to open a PR for this. It would include:

- Setup up a pre-commit config for code formatting.
- Add a code formatting check to your existing CI.
- Blacken the code base.

**Comment by martindurant** [comment]
I agree that it is good to have a standard, but I must admit that I don't particularly like Black's standard settings beyond normal pep8 rules, particularly expanding argument sets into many lines.

**Comment by asford** [comment]
Honestly, I agree that some of black's opinions don't match what I'd prefer but I've found that the extreme predictability and consistency it provides is worth it.

My strong request would be more for some form of pre-commit enforced code style I can adopt when working on PRs. Given that dask has gone with black, and that it's becoming a standard across many popular projects, it seems like a natural default choice but a yapf configuration would also be an option. Happy to defer to your preference here.

**Comment by martindurant** [comment]
OK, do black I suppose. I can live with it.

**Comment by asford** [comment]
.  R
