### ISSUE TITLE
issue with ftp traversal, KeyError "name"

### ISSUE THREAD

**Issue by hardingnj** [intake/filesystem_spec#135]
I think this is a bug (version `0.4.4`), caused by some entries (`cdir` and `pdir`) on FTP not having the `name` attribute. Very happy to submit a PR if so, should be a straightforward fix.

```
import fsspec
host = fsspec.filesystem('ftp', host='ngs.sanger.ac.uk') 
host.ls(".")
```
gives:
```
[{'modify': '20180615104058',
  'perm': 'fle',
  'type': 'cdir',
  'unique': 'FC02U80',
  'unix.group': '0',
  'unix.mode': '0755',
  'unix.owner': '0'},
 {'modify': '20180615104058',
  'perm': 'fle',
  'type': 'pdir',
  'unique': 'FC02U80',
  'unix.group': '0',
  'unix.mode': '0755',
  'unix.owner': '0'},
 {'modify': '20190513162006',
  'perm': 'fle',
  'type': 'dir',
  'unique': 'FC02U83',
  'unix.group': '0',
  'unix.mode': '0755',
  'unix.owner': '0',
  'name': '/./production',
  'size': 0},
 {'modify': '20180615104110',
  'perm': 'fle',
  'type': 'dir',
  'unique': 'FC02U80000080',
  'unix.group': '0',
  'unix.mode': '0755',
  'unix.owner': '0',
  'name': '/./scratch',
  'size': 0},
 {'modify': '20180119093730',
  'perm': 'adfr',
  'size': 1099,
  'type': 'file',
  'unique': 'FC02U3937',
  'unix.group': '0',
  'unix.mode': '0644',
  'unix.owner': '0',
  'name': '/./README'}]
```

but
```
host.open("README")
```
gives:
```
...

~/git/vector-ops/binder/deps/conda/envs/vector-ops-c668a73/lib/python3.6/site-packages/fsspec/implementations/ftp.py in <listcomp>(.0)
    108         path = self._strip_protocol(path)
    109         files = self.ls(self._parent(path), True)
--> 110         return [f for f in files if f['name'] == path][0]
    111 
    112     def _open(self, path, mode='rb', block_size=None, autocommit=True,

KeyError: 'name'
```
I guess because when traversing `pdir` or `cdir`, it fails to find the attribute. Perhaps because line  `109` is not functioning as intended in allowing dirs as well?

**Comment by martindurant** [comment]
Converting cdir, pdir -> dir fixes this? I must admit I don't know what those other labels mean.

**Comment by hardingnj** [comment]
I think they mean current dir and parent dir, i.e. `./` and `../`. 

Not sure what you mean by convert here?

**Comment by martindurant** [comment]
Oh OK, then they should be removed, right?

**Comment by hardingnj** [comment]
Yes, and I think normal dirs should be excluded to. Maybe:

`files = self.ls(self._parent(path), True)` 
 to
`files = [x for x in self.ls(self._parent(path), detail=True) if x['type'] == 'file']`

**Comment by hardingnj** [comment]
if that looks reasonable I can make a small PR.

**Comment by martindurant** [comment]
Please do put it in a PR. I am not certain about excluding normal dirs, I haven't looked at the snippet of code yet.
