### ISSUE TITLE
AbstractFileSystem walk method calls ls with 3 parameters, but only 2 expected

### ISSUE THREAD

**Issue by jonathan-hourany** [intake/filesystem_spec#166]
Although `ls` is expected to be overwritten by child classes, it's still worth noting that the `walk` method passes 3 arguments (2 positional and `**kwargs`) 

https://github.com/intake/filesystem_spec/blob/d774f0ef92b5f7bd28ec0b1b4e4fdb62ee8bea60/fsspec/spec.py#L344

While `ls` only accepts 1 position and `**kwargs`
https://github.com/intake/filesystem_spec/blob/d774f0ef92b5f7bd28ec0b1b4e4fdb62ee8bea60/fsspec/spec.py#L264

This causes `TypeError` to be raised instead of the expected `NotImplementedError`. Looking at the docstring for `ls`, it looks like walk should be called with `detail=True` or `ls` changed to have "detail" explicitly declared in the function signature (or both).

**Comment by martindurant** [comment]
Indeed, should be `ls(self, path, detail=True, **kwargs)`. Would be happy to see this changed in both places.
