### ISSUE TITLE
AbstractFileSystem and pyarrow.filesystem.DaskFilesystem

### ISSUE THREAD

**Issue by TomAugspurger** [intake/filesystem_spec#176]
Trying to understand the base class handling for AbstractFileSystem.

I see that when pyarrow is around, we have DaskFileSystem as a base class.

```python
In [25]: import s3fs

In [26]: import pyarrow as pa

In [27]: fs = s3fs.S3FileSystem(token="anon")

In [28]: isinstance(fs, pa.filesystem.DaskFileSystem)
Out[28]: True
```

However, because we don't call `super().__init__`, many methods inherited will fail.

```pytb
In [29]: fs.delete("/a/b")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-5c40cbeb5a73> in <module>
----> 1 fs.delete("/a/b")

~/miniconda3/envs/filesystems/lib/python3.7/site-packages/pyarrow/filesystem.py in delete(self, path, recursive)
    283     def delete(self, path, recursive=False):
    284         path = _stringify_path(path)
--> 285         return self.fs.rm(path, recursive=recursive)
    286
    287     @implements(FileSystem.exists)

AttributeError: 'S3FileSystem' object has no attribute 'fs'
```

So my primary question is why is having DaskFileSystem as a base class valuable? Presumably it's so that pyarrow will accept these objects? I just didn't immediately understand this design.

cc @martindurant if you have some context / links to issues where this was discussed.

**Comment by TomAugspurger** [comment]
Gotcha.

I'm going to open a JIRA to see why pyarrow isn't ducktyping.

**Comment by TomAugspurger** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-7102 on Arrow. That proposes replacing the current pyarrow S3FSWrapper with a generic FSSpecWrapper, which would let pyarrow work with any spec-compliant implementation.

**Comment by jorisvandenbossche** [comment]
I think this issue can be closed, now the AbstractFileSystem no longer inherits from pyarrow
