### ISSUE TITLE
alternative serializations (json?)

### ISSUE THREAD

**Issue by lukasheinrich** [intake/filesystem_spec#199]
I'm interested in a layer that allows to consistently pass file-like obects between e.g. languages, and was wondering whether fsspec would be the right tool as serializability of file-like entities seems to be a priority. Would alternative serializations to pickle/cloudpickle be in-scope?

**Comment by TomAugspurger** [comment]
Can you provide a few more details about how this would be used? What would be serialized, the filesystem, or the files?

**Comment by lukasheinrich** [comment]
my understanding is that when I serialize a `OpenFile` object with pickle / cloudpickle, it's more like a descriptive reference to the FS-type and file identifier (or path) 

```
>>> pickle.dumps(fsspec.open('http://hello/world.txt'))
b'\x80\x03cfsspec.core\nOpenFile\nq\x00(cfsspec.spec\nmake_instance\nq\x01cfsspec.implementations.http\nHTTPFileSystem\nq\x02)}q\x03\x87q\x04Rq\x05X\x16\x00\x00\x00http://hello/world.txtq\x06X\x02\x00\x00\x00rbq\x07NX\x04\x00\x00\x00utf8q\x08Ntq\tRq\n.'
```

which I naively would have thought, could be also serialized as 

```
{"type": "fsspec.filesysteps.http","path": "http://hello/world.txt"}
```

or similar (maybe even JSON-LD?) such that the spec is not python-only but could reasonably be read by a worker process in some other language. 

Consider e.g. a zero-mq channel which gets populated by a python process, but read back by a C++ process

**Comment by martindurant** [comment]
Yes, you could certainly make such a serialisation: currently the reduce paradigm encodes a set of simple types like strings and dicts. However, the *meaning* of those values is tied to each implementation, so if you wanted to map to some implementation in another language, you'd have to unpack them based on the current set of arguments for the given python class. That doesn't sound too tractable (and also would fail for pickle whenever the API changes).

```
>>> fsspec.open('http://hello/world.txt').__reduce__()
(fsspec.core.OpenFile,
 (<fsspec.implementations.http.HTTPFileSystem at 0x1173aac50>,
  'http://hello/world.txt',
  'rb',
  None,
  'utf8',
  None))
```

**Comment by TomAugspurger** [comment]
I'd recommend a `to_json()` method, rather than trying to use interpret the output intended for pickle.

**Comment by martindurant** [comment]
Agreed, I was only pointing out that we already make something that looks like it ought to be JSON friendly. I would rewrite the FS class for its protocol, a string.

**Comment by lukasheinrich** [comment]
yes certainly each language implementation would have to implement code to turn such a JSON object back into an actual file object, but at least the serialization format would be standardized. In some sense it already is using the URI scheme a la `s3://`, `file://`, however, things like the `mode` and `encoding` are not captured by the URI. I could see value in defining such a JSON(-LD) spec though wasn't sure if that's for fsspec

**Comment by martindurant** [comment]
I think it could make sense for fsspec to have an opinion on this, for others to opt into, if they want.
