### ISSUE TITLE
Use entrypoints for known implementations

### ISSUE THREAD

**Issue by TomAugspurger** [intake/filesystem_spec#206]
Right now, adding a new implementation to the dict of `known_implementations` requires some coordination between fsspec and the downstream library. This might include the downstream library mutating `known_implementations` as a side-effect of importing the library.

An alternative is to have fsspec add an entrypoint for implementations, and downstream libraries would add themselves to it.

**Comment by martindurant** [comment]
This would require other packages outside of fsspec to participate by publishing their protocol entrypoints, but would remove the requirement for them to be either listed in known_implementations in this package or to modify the registry at import time.

**Comment by hayesgb** [comment]
@martindurant -- Do you want to list either of the abfs:// or adl:// protocols in the fsspec known_implementations, of should I go the route of entrypoints/

**Comment by TomAugspurger** [comment]
I think those choices are independent. You can register multiple
entrypoints within the ffspec group.

**Comment by martindurant** [comment]
Did you already implement the entrypoints way in fsspec? In that case that should be the way. If not, a PR to fsspec adding the entries to known_implementations.

**Comment by TomAugspurger** [comment]
No, I haven't implemented it yet. I can later today if there's interest.

**Comment by martindurant** [comment]
OK, so that's for the future. We want people to be accessing Azure right now, so lets add it into fsspec known_implementations forthwith.
