### ISSUE TITLE
Shouldn't 'walk' return 'info' instead of just name?

### ISSUE THREAD

**Issue by ivannp** [intake/filesystem_spec#214]
Have been working on a tiny wrapper (mostly put/get functionality, no need of _open) around [Google Drive](https://developers.google.com/drive/api/v3/about-sdk) - _gdrivefs_.

One thing I noticed is that _walk_ doesn't return the object infos. Is there a reason for this?

In my case this will double the necessary remote calls to retrieve the file info. Hence, I don't want to use the provided _walk_, so if it's not going to change (to provide a fourth array with the infos) - I will overwrite it in _gdrivefs_.

If you are wondering in what context I need this - I am porting [a cloud storage sync application](https://github.com/ivannp/cync) from C# to Python. In the process, I came across fsspec and decided it to use it - very nice and has similar functionality to the fs abstraction I have in my project.

**Comment by martindurant** [comment]
You should checkout another [gcloudfs](https://github.com/intake/gdrivefs), which also uses filelistings caching and ought to get around your double-call problem.

As to the API for `walk()`, this is taken from the builtin python version, so I don't think we really have scope to change it. There could, I suppose, be an optional flag.

**Comment by dhirschfeld** [comment]
I'm also running into this so would be very much in favour of an optional flag:
```
fs.walk(return_info=False)
```

**Comment by martindurant** [comment]
Perhaps it should, then, be a different method name?

**Comment by dhirschfeld** [comment]
A method which returns different types depending on the value of an argument is often considered a bit of a code smell, but in python I think it's ok - at the end of the day they're all just PyObjects anyway ;)

I guess a consideration is that if you change the argument value you'll have to refactor the code to handle the new return type, however, if you changed the method name you'd still have to refactor your code in exactly the same way so I don't see any benefit there.

If the only benefit to a new method is confirming to some sense of *"purity"* I think the argument is the better way to go as there is a usability cost to increasing the api size (number of distinct methods)

**Comment by dhirschfeld** [comment]
One way to minimise any required refactoring would be to return an `Iterable[filepath]`

In the case where `return_info=False` the concrete return type could be `List[filepath]` whereas if `return_info=True` it could return `Dict[filepath, dict]` with the nested dict containing the fileinfo keyed by the filepath

**Comment by martindurant** [comment]
OK, well so long as the default stays the same. Would you like to make this a PR?

**Comment by martindurant** [comment]
Does https://github.com/intake/filesystem_spec/pull/116 address this?

**Comment by dhirschfeld** [comment]
Yep - looks like that's exactly what I'm after!
