### ISSUE TITLE
Standardize dircache timeout

### ISSUE THREAD

**Issue by TomAugspurger** [intake/filesystem_spec#215]
Currently gcsfs implements a `cache_timeout` and s3fs might want one too (https://github.com/dask/s3fs/issues/271, https://github.com/dask/s3fs/issues/253). So maybe we should just add it to AbstractFileSystem.

**Proposal**

Adds a `cache_timeout` to  `AbstractFileSystem.__init__`. Taken from the gcsfs docs

```
    cache_timeout: float, optional
        Cache expiration time in seconds for object metadata cache.
        Set cache_timeout <= 0 for no caching, None for no cache expiration.
```

As for the default, I think `None` makes the most sense for now since that's what gcsfs does. We can explore deprecating `None` in favor of something else (I think `0` for no caching) down the road.

One question: is this timeout per-key, per-directory, or global to the filesystem instance? In the gcsfs docs, we state

```
GCSFileSystem maintains a per-implied-directory cache of object listings and
    fulfills all object information and listing requests from cache. 
```

But from what I can tell, the cache is actually **per object**, not per-directory.

```python
    @_tracemethod
    def _list_objects(self, path):
        ...
        listing = self._do_list_objects(path)
        retrieved_time = time.time()

        self._listing_cache[path] = (retrieved_time, listing)
        return listing
```

and

```python
    @_tracemethod
    def _maybe_get_cached_listing(self, path):
        ...
        if path in self._listing_cache:
            retrieved_time, listing = self._listing_cache[path]
            cache_age = time.time() - retrieved_time
            if self.cache_timeout is not None and cache_age > self.cache_timeout:
                logger.debug(
                    "expired cache path: %s retrieved_time: %.3f cache_age: "
                    "%.3f cache_timeout: %.3f",
                    path,
                    retrieved_time,
                    cache_age,
                    self.cache_timeout,
                )
                del self._listing_cache[path]
                return None

            return listing

        return None
```

**Comment by TomAugspurger** [comment]
cc @martindurant

**Comment by martindurant** [comment]
Should be per listing, i.e., a directory of stuff. A listing could be a single key-item in the case that the parent hadn't been previously listed.
