### ISSUE TITLE
Question about next release

### ISSUE THREAD

**Issue by hayesgb** [intake/filesystem_spec#220]
Wondering if you know when the next release may come out?  The `adl://` and `abfs://` protocols from [adlfs](https://github.com/dask/adlfs) are currently available in the registry of fsspec's master branch.  Wondering when I can plan to remove conditional declarations for the fsspec registry?

Sharing the discussion from [here](https://github.com/dask/adlfs/issues/22).

Thanks,
Greg

**Comment by TomAugspurger** [comment]
I'll do a release later today.

**Comment by TomAugspurger** [comment]
Just released 0.6.2 on PyPI https://pypi.org/project/fsspec/

Should show up on Conda-forge in an hour or so.

**Comment by martindurant** [comment]
Now we can update the text in the dask pages
