### ISSUE TITLE
FTPFileSystem.open raises exception

### ISSUE THREAD

**Issue by dhirschfeld** [intake/filesystem_spec#225]
With the FTP I'm using, trying to open a file raises `ftplib.error_temp: 426 Nothing to abort`
```python
import fsspec


fs = fsspec.filesystem('ftp', **kwargs)
files = fs.ls('/')
filename = files[0]['name']
with fs.open(filename, 'rb') as f:
    content = f.read()
```
```python-traceback
Traceback (most recent call last):
  File "C:\Users\dhirschf\envs\dev\lib\site-packages\fsspec\implementations\ftp.py", line 242, in _fetch_range
    callback=callback,
  File "C:\Users\dhirschf\envs\dev\lib\ftplib.py", line 447, in retrbinary
    callback(data)
  File "C:\Users\dhirschf\envs\dev\lib\site-packages\fsspec\implementations\ftp.py", line 235, in callback
    raise TransferDone
fsspec.implementations.ftp.TransferDone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/dhirschf/.PyCharm2019.3/config/scratches/scratch_5.py", line 12, in <module>
    content = f.read()
  File "C:\Users\dhirschf\envs\dev\lib\site-packages\fsspec\spec.py", line 1130, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "C:\Users\dhirschf\envs\dev\lib\site-packages\fsspec\caching.py", line 156, in _fetch
    self.cache = self.fetcher(start, end)  # new block replaces old
  File "C:\Users\dhirschf\envs\dev\lib\site-packages\fsspec\implementations\ftp.py", line 247, in _fetch_range
    self.fs.ftp.voidresp()
  File "C:\Users\dhirschf\envs\dev\lib\ftplib.py", line 251, in voidresp
    resp = self.getresp()
  File "C:\Users\dhirschf\envs\dev\lib\ftplib.py", line 244, in getresp
    raise error_temp(resp)
ftplib.error_temp: 426 Nothing to abort.
```
https://github.com/intake/filesystem_spec/blob/b7b60092898b90b56124a9b3d983a21055c0b4b3/fsspec/implementations/ftp.py#L237-L250

...so it's actually the call to `voidresp` which fails (after the abort call appears to work correctly - returning a 226).

[**`ftplib.py`**](https://github.com/python/cpython/blob/efa3b51fd060352cc6220b27a1026e4d4d5401bd/Lib/ftplib.py#L246)
![image](https://user-images.githubusercontent.com/881019/71788588-79221000-306f-11ea-87fe-92e5951cca96.png)

**Comment by dhirschfeld** [comment]
```python
In [23]: fsspec.__version__
Out[23]: '0.6.2'

In [24]: sys.version
Out[24]: '3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]'

In [25]: platform.platform()
Out[25]: 'Windows-10-10.0.17763-SP0'
```

**Comment by dhirschfeld** [comment]
What's the point of the abort/voidresp? If I patch it like below everything (seem to) work fine!
```python
        except TransferDone:
            try:
                self.fs.ftp.abort()
                self.fs.ftp.voidresp()
            except timeout:
                self.fs._connect()
            except Exception:
                pass
        return b"".join(out)
```
![image](https://user-images.githubusercontent.com/881019/71788858-07979100-3072-11ea-86ec-fd1b50fa12b6.png)

**Comment by martindurant** [comment]
The abort/void exists, because FTP only allows to specify the starting offset of the transfer, not the end; so in the typical case that there are more than blocksize bytes to come, we need to interrupt the transfer. The void call makes sure that we allow the abort to be processed (which is why you don't see the exception until then).

Perhaps in your case everything could be sent in one block? I would not have thought that aborting when there is nothing to abort should be an exception. Catching the (specific) exception seems like a reasonable thing to do, though it would be good to see what conditions cause this.

**Comment by dhirschfeld** [comment]
All my files are tiny so it's likely they're all received in a single block. I'll see about putting in a PR to specifically ignore the 426 error in this case...

**Comment by martindurant** [comment]
@dhirschfeld , I suspect that the error may also be specific to your server implementation (all FTPs are different); but I do think that catching the exception is a good idea.

**Comment by martindurant** [comment]
Would you like to post this like a PR to ignore the exception if it happens and not to abort at all if it's the last block?

**Comment by dhirschfeld** [comment]
Yep, sure - just a bit short on time. Can try to get to that this week but feel free to do so yourself if you want it in quicker than that...
