### ISSUE TITLE
Release of dropbox implementation

### ISSUE THREAD

**Issue by MarineChap** [intake/filesystem_spec#226]
The dropbox implementation have been release in pypi under the module dropboxdrivefs. 
The code is available in my repository [intake_dropbox]( https://github.com/MarineChap/intake_dropbox )

It is ready to be used in fsspec with the protocole '"dropbox"

Don't hesitate to give me feedback, comments, questions

**Comment by martindurant** [comment]
Dropbox is now linked from https://filesystem-spec.readthedocs.io/en/latest/api.html#other-known-implementations , so this issue can be closed,
