### ISSUE TITLE
use pooch for file caching

### ISSUE THREAD

**Issue by martindurant** [intake/filesystem_spec#227]
Ref: https://github.com/fatiando/pooch/pull/134

[Pooch](https://www.fatiando.org/pooch/latest/) is a package explicitly for the downloading of data filed from HTTP and FTP. It has a file-based registry pointing to URLs and contains optional extra information and checksums. Writing an implementation for fsspec would be trivial, such that the following would be possible:

    of = fsspec.open('pooch://afile.csv', registry='myfile')

and thus include pooch downloading in dask or intake.

**Comment by leouieda** [comment]
Hum, that would be interesting. What would be a potential use case for this? I could think of a package author having a Pooch registry file but importing `fsspec` instead to open the files instead of `pooch`. Is that what you had in mind?

**Comment by martindurant** [comment]
Exactly, or anything else that uses fsspec natively, such as Intake or Dask. Additionally, you might, for instance, glob over pooch files or perform other more file-system-like operations (anything more than open).
Indeed, pooch being so specific, you could imagine that the registry spec (including checksum and version definitions) is what Pooch really brings, so it would be conceivable for fsspec to completely reproduce that functionality by itself, if you were interested in implementing that. (otoh, pooch is, of course, very lightweight in itself)
