### ISSUE TITLE
get_fs_token_paths not in API docs

### ISSUE THREAD

**Issue by oliverwm1** [intake/filesystem_spec#237]
Is the function `get_fs_token_paths` intended for public use? This is a very useful feature that I have found myself reimplementing in order to use filesystem object functions (e.g. `ls`, `exists`) without knowing a priori what filesystem a urlpath corresponds to.

**Comment by martindurant** [comment]
Yes, I believe it should be exposed/documented as something that lower-level users of the library might find useful.

**Comment by martindurant** [comment]
https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.core.get_fs_token_paths
