### ISSUE TITLE
Issue with sftp protocol

### ISSUE THREAD

**Issue by MarineChap** [intake/filesystem_spec#242]
Hello ! 
I am trying to use intake with the sftp implementation. 

The _get_kwargs_from_urls is not correctly selecting the path (by keeping "/" in front of the path) making paramiko failed for not finding the file. 

The bug happen when the urlpath look like this : `ssh://host/path `
the final path is `/path` instead of `path`. 

It makes it impossible to use intake catalog with this implementation. 

Also, the host is mandatory in the urlpath. Is that something wanted ? Why it cannot just be added to to ssh_options ? 
Do you think I am correctly setting the path or there is another way that avoid the problem ?

Thank you

**Comment by MarineChap** [comment]
I can fix this issue by setting the whole path from the root. I think it should be added somewhere in the documentation as it is a different behavior as paramiko.

**Comment by martindurant** [comment]
> I can fix this issue by setting the whole path from the root.

What do you mean by this?

**Comment by MarineChap** [comment]
Maybe it is a really specific problem in fact... 
So, in my lab, we have a cluster accessible from 3 different hostnames. 
If I put the path starting from where I arrive when connecting with the username chosen, `username/path/file`,  it works with paramiko but it gives `file not found` for the sftp implementation, mainly because of it "/" added at the beginning of the path. 

Now, If I am looking to the full path of my file, it is something like `"/export/path/username/path/file"`. In that case, it is working as the "/" kept by the implement is indeed part of the path. 

It is more clear like this?

**Comment by martindurant** [comment]
Ah right, so `"username/path/file"` is seen as a path relative to some home or current directory.
Paramiko has a `getcwd` method, but I don't know how we would tell the difference from the URL alone, as to whether the user wanted a relative or absolute location.

Where you actually instantiate the class `fs = fsspec.filesystem('sftp', ...)` and then call `fs.method(...)` then you have the opportunity to use the initial "/" or not.

**Comment by MarineChap** [comment]
I want to use it from an intake catalog. So, I don't have the hand on it, right ? 
But at the end, It is not a huge problem, maybe just add some documentation to be clear about it and that's enough.

**Comment by martindurant** [comment]
Correct, if you are using Intake, and therefore the implicit URL parsing, I don't see how you can specify that your path is meant to be relative.

**Comment by MarineChap** [comment]
To resume, if using with intake, the only solution is to use it with absolute path, which is fine for my use-case. 
Thanks for your help.

**Comment by martindurant** [comment]
I will put note in the SFTPFileSystem docstring - but it's not obvious that a user of Intake would know to look there, so the Intake doc will need some changes too.
