### ISSUE TITLE
CachingFileSystem not thread-safe

### ISSUE THREAD

**Issue by SeguinBe** [intake/filesystem_spec#249]
Hello,

Wonderful library that I start to use extensively!

Maybe it would be good to specify in the documentation that `CachingFileSystem` is not suited to a concurrent use? It seems to be using temporary file moving which are not atomic operations and fail in a conccurent setting.

**Comment by martindurant** [comment]
See https://github.com/intake/filesystem_spec/pull/248/files#diff-fd28cf28001d94bc7d51f2fe0d6f9823R155

That line makes at least the move part atomic. The temporary file should probably be unique each time? Otherwise, the cache is additive, and my thought was, that an overwrite from another thread may miss some files (causing a repeat download), it would not cause inconsistency.

**Comment by SeguinBe** [comment]
yeah there is an issue because different threads try to modify the same file, and `os.replace` being called concurrently creates a `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/files/cache.temp' -> '/tmp/files/cache'`

**Comment by martindurant** [comment]
Can you make a test case demonstrating that, and then we can (try to) find a solution for it? Otherwise you are right, documentation should be provided.

**Comment by martindurant** [comment]
The following is my unique files suggestion
```diff
--- a/fsspec/implementations/cached.py
+++ b/fsspec/implementations/cached.py
@@ -150,9 +150,10 @@ class CachingFileSystem(AbstractFileSystem):
         for c in cache.values():
             if isinstance(c["blocks"], set):
                 c["blocks"] = list(c["blocks"])
-        with open(fn + ".temp", "wb") as f:
+        fn2 = tempfile.mktemp()
+        with open(fn2, "wb") as f:
             pickle.dump(cache, f)
-        os.replace(fn + ".temp", fn)
+        os.replace(fn2, fn)
```

**Comment by SeguinBe** [comment]
Things happen behind the `DataLoader` of `pytorch`, but something relatively equivalent to my usecase would be:

```python
import fsspec
from concurrent.futures import ProcessPoolExecutor
fs_cached = fsspec.filesystem("filecache", target_protocol='gcs', cache_storage='/tmp/files/')
filenames = []  # Lots of gs:// filenames

def _fn(filename):
    with fs_cached.open(filename, 'rb') as f:
        f.read()

with ProcessPoolExecutor(8) as e:
    e.map(_fn, filenames)

```

**Comment by SeguinBe** [comment]
At the moment I have replaced the file caching with `joblib.Memory` which behaves better in multi threaded environments

**Comment by martindurant** [comment]
I tried your code, above, with local files (962 files in /usr/bin !) and the diff I posted above and got no error.

**Comment by SeguinBe** [comment]
I load 50k files that way, it is good that there are no errors but I'd expect significant unnecessary downloads with this approach no?

**Comment by martindurant** [comment]
> significant unnecessary downloads

Only if the time to write the pickle and move the file is significant compared to the time to download the file, which seems unlikely. More logging in the FS would be useful here..., however, does my change solve your problem?

In the common case that expiry and UID checking are not required, the cache metadata file isn't actually required, so may be reasonable to have a shortcut. Otherwise, we'd be looking at a way to merge atomic inserts from multiple processes, i.e., some database method.

By the way, how is performance with 50000 files in a single directory?

**Comment by SeguinBe** [comment]
Well given the fact that I have 50k small image files (deep learning dataset), each file is 100kB but the pickle holding everything would probably be much bigger, and most likely would be quite slow as it needs to be completely rewritten at every cache save.

Yeah, in my situation I assume data to be static, which is the only reason why it could be achieved without a form of a database or key-value store of some sort.

Surprisingly, no issue at all with that many files in the same directory.

Usually, I would group files in bigger blocks as it is standard for datasets, but here I can not as I need to have random accesses to them because of the peculiarities of the training I'm doing.

**Comment by martindurant** [comment]
If you are interested in delving further, something like the following should work, using `os.path.exists` to test for a file already having been downloaded, and no cache file at all. This is still fragile to two processes accessing the same cached file at the same time
```python
class SimpleCache(WholeFileCacheFileSystem):

    protocol = "simplecache"

    def __init__(
            self,
            target_protocol=None,
            cache_storage="TMP",
            target_options=None,
            **kwargs
    ):
        super().__init__(
            target_protocol=target_protocol,
            target_options=target_options,
            cache_storage=cache_storage,
            cache_check=False,
            expiry_time=False,
            check_files=False,
            **kwargs
        )

    def _check_cache(self):
        pass

    def save_cache(self):
        pass

    def load_cache(self):
        pass

    def _check_file(self, path):
        if not path.startswith(self.target_protocol):
            store_path = self.target_protocol + "://" + path
            path = self.fs._strip_protocol(store_path)
        hash = hashlib.sha256(path.encode()).hexdigest()
        for storage in self.storage:
            fn = os.path.join(storage, hash)
            if os.path.exists(fn):
                detail = {
                    "fn": hash,
                    "blocks": True,
                }
                return detail, fn
```
This basically replaces methods that act on the cache metadata with no-ops.

**Comment by martindurant** [comment]
For your *specific* case, it would also make sense to include an option to sub-hash into a user-specified number of directories. How many options do you need? :)

**Comment by martindurant** [comment]
Here is a version of the cache without the metadata that works, as a drop-in for the existing whole file cache. Care to test?
```python
class WholeFileCacheFileSystem(CachingFileSystem):

    protocol = "filecache"

    def __init__(
            self,
            target_protocol=None,
            cache_storage="TMP",
            target_options=None,
            **kwargs
    ):
        for key in ['cache_check', 'expiry_time', 'check_files']:
            kwargs.pop(key, None)
        super().__init__(
            target_protocol=target_protocol,
            target_options=target_options,
            cache_storage=cache_storage,
            cache_check=False,
            expiry_time=False,
            check_files=False,
            **kwargs
        )
        for storage in self.storage:
            if not os.path.exists(storage):
                os.makedirs(storage, exist_ok=True)
        self.cached_files = [{}]

    def _check_file(self, path):
        sha = hashlib.sha256(path.encode()).hexdigest()
        for storage in self.storage:
            fn = os.path.join(storage, sha)
            if os.path.exists(fn):
                return fn

    def _open(self, path, mode="rb", **kwargs):
        path = self._strip_protocol(path)

        if not path.startswith(self.target_protocol):
            store_path = self.target_protocol + "://" + path
            path = self.fs._strip_protocol(store_path)
        if mode != "rb":
            return self.fs._open(path, mode=mode, **kwargs)
        fn = self._check_file(path)
        if fn:
            return open(fn, "rb")

        sha = hashlib.sha256(path.encode()).hexdigest()
        fn = os.path.join(self.storage[-1], sha)
        logger.debug("Copying %s to local cache" % path)
        kwargs["mode"] = mode

        with self.fs._open(path, **kwargs) as f, open(fn, "wb") as f2:
            if isinstance(f, AbstractBufferedFile):
                # want no type of caching if just downloading whole thing
                f.cache = BaseCache(0, f.cache.fetcher, f.size)
            if getattr(f, "blocksize", 0) and f.size:
                # opportunity to parallelise here
                data = True
                while data:
                    data = f.read(f.blocksize)
                    f2.write(data)
            else:
                # this only applies to HTTP, should instead use streaming
                f2.write(f.read())
        return self._open(path, mode)
```
