### ISSUE TITLE
test_strip_protocol_expanduser assumes home paths

### ISSUE THREAD

**Issue by QuLogic** [intake/filesystem_spec#253]
`test_strip_protocol_expanduser` assumes that `$USER` is part of the path of `$HOME`, but there's no requirement for that to be so.

**Comment by ArchangeGabriel** [comment]
Indeed, and that’s the only failing test for me:
```
________________________ test_strip_protocol_expanduser ________________________

    def test_strip_protocol_expanduser():
        path = "file://~\\foo\\bar" if sys.platform == "win32" else "file://~/foo/bar"
        stripped = LocalFileSystem._strip_protocol(path)
        assert path != stripped
        assert "file://" not in stripped
>       assert getpass.getuser() in stripped
E       AssertionError: assert 'builduser' in '/build/foo/bar'
E        +  where 'builduser' = <function getuser at 0x7f09ba45b670>()
E        +    where <function getuser at 0x7f09ba45b670> = getpass.getuser

fsspec/implementations/tests/test_local.py:472: AssertionError
```

**Comment by martindurant** [comment]
Is there a foolproof way to test this? I'm not sure that HOME is always the right variable either.
Happy to see a PR that generalises the test.

**Comment by ArchangeGabriel** [comment]
I’m not sure what you want to test actually, so…

**Comment by martindurant** [comment]
The intended functionality is that a `"~"` character in a local path is expanded to the user's home directory. How should we ensure that this is working correctly? Apparently the current test does the wrong thing on your system (i.e., `LocalFileSystem._strip_protocol` does the right thing, but the test is wrong).

**Comment by ArchangeGabriel** [comment]
I guess the issue is `in a portable way`… I can only speak for Linux, but the home can be retrieved either with `$HOME` or `getent passwd $USER`.

A little SX-fu returns [this](https://stackoverflow.com/a/4028943). But then it’s using `~` too, so not sure what this proves…

**Comment by martindurant** [comment]
> I can only speak for Linux

That is exactly the problem. 
I suppose we could call `expanduser("~")` in the test itself?

**Comment by ArchangeGabriel** [comment]
Yes, you could check whether this is a strict prefix of `stripped` even. But I don’t know what resolves `~` in your code and in `os.path`, so I’m not sure whether they could fail both for instance.

**Comment by martindurant** [comment]
`LocalFileSystem` also calls `expanduser`, so essentially the check becomes: did the fsspec code actually make the call or not, and we can assume that the python stdlib did the right thing.
Would you like to implement this change to the test as a PR, and see that it passes for you?

**Comment by ArchangeGabriel** [comment]
If you are satisfied with this new meaning of the check, yes, I can have a take at it.

**Comment by martindurant** [comment]
Yes, I think so, thanks.

**Comment by ArchangeGabriel** [comment]
#364
