### ISSUE TITLE
webhdfs logger not support python3

### ISSUE THREAD

**Issue by hohdiy** [intake/filesystem_spec#261]
https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/webhdfs.py
![image](https://user-images.githubusercontent.com/20314800/77874762-95a1a300-7280-11ea-93b1-9e508262d8f2.png)

**Comment by hohdiy** [comment]
TypeError: not all arguments converted during string formatting
because:
url is str
method is str
args is dict
but **def debug(self, msg, *args, **kwargs):**

**Comment by martindurant** [comment]
This is surprising - fsspec is written for py3 only; and the tests do pass.
I believe that in the signature
```
def debug(self, msg, *args, **kwargs):
```
when called with 
```
logger.debug(url, method, args)
```
with `args` as a dict, will end up with
```
args_in_debug = (args_dict,)
```

This might not be quite the intended output, but should not break anything.
