### ISSUE TITLE
MemoryFileSystem recursive remove inconsistencies

### ISSUE THREAD

**Issue by ryanSoley** [intake/filesystem_spec#264]
I'm using the `MemoryFileSystem` to test a class that leverages either the `LocalFileSystem` or `S3FileSystem` during normal usage and noticed an issue with the memory implementation's recursive remove.

```python
>>> import fsspec
>>> fs = fsspec.filesystem("memory")
>>> fs.touch("root/dir/file.txt")
>>> fs.ls("root/")
['root/dir/']
>>> fs.ls("root/dir")
['root/dir/file.txt']
>>> fs.rm("root/dir", recursive=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nvd215/miniconda3/envs/positron/lib/python3.7/site-packages/fsspec/spec.py", line 651, in rm
    self.rmdir(pa_)
  File "/Users/nvd215/miniconda3/envs/positron/lib/python3.7/site-packages/fsspec/implementations/memory.py", line 96, in rmdir
    raise FileNotFoundError(path)
FileNotFoundError: root/dir
>>> fs.ls("root/")
[]
``` 

In the example above, there's an error thrown but an `ls` shows that the directory was actually removed as expected. Looks like `rm("root/dir/file.txt")` was successfully executed but the recursive call to `rm("root/dir")` is what errored.

The error may be more with how the paths are stored, rather than the remove itself, because similar errors come up in `rmdir`.

```python
>>> fs.touch("root/dir/file.txt")
>>> fs.ls("root/")
['root/dir/']
>>> fs.rmdir("root/dir")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nvd215/miniconda3/envs/positron/lib/python3.7/site-packages/fsspec/implementations/memory.py", line 96, in rmdir
    raise FileNotFoundError(path)
FileNotFoundError: root/dir
```

I expected the `rmdir` call above to [error because the directory is not empty](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/memory.py#L94), but it doesn't even get to that point.

It seems like either `MemoryFile.commit` needs to write each element of the path to the store dictionary, or the remove functions need some way to infer the nested directories [like `ls` does](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/memory.py#L32).

**Comment by martindurant** [comment]
Probably rmdir should be a no-op, since empty directories do not exist. It could perhaps error, as you suggest, if there are lower-level paths present.

**Comment by ryanSoley** [comment]
Yea a no-op would work if we don't mind not erroring when there are lower level paths.

It looks like [`pseudo_dirs`](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/memory.py#L14) was intended to deal with this, but the list isn't populated when a file is committed. I patched `MemoryFile.commit` with this and then the removes worked as expected (most errors included).

```python
def patch_commit(self):
    pseudo_dir = ""
    
    for part in self.path.strip("/").rstrip("/").split("/")[:-1]:
        pseudo_dir += f"/{part}"
        
        if pseudo_dir not in self.fs.pseudo_dirs:
            self.fs.pseudo_dirs.append(pseudo_dir)
        
    self.fs.store[self.path] = self

fsspec.implementations.memory.MemoryFile.commit = patch_commit
```

This does cause duplicated directories to appear in calls to `ls`, but I think that's because `ls` was designed to work correctly without `pseudo_dirs` populated. When there are entries in `pseudo_dirs`, [this block](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/memory.py#L76) introduces duplicates.

Removing that block in another patch, thus removing duplicates from `ls` results, looks like it makes most things work properly. (The call to `ls` in `walk` returning duplicates was resulting in some new errors with recursive remove.)

**Comment by martindurant** [comment]
Can you please make this into a PR with tests to show correct behaviour? It's the lack of testing that leads to this problem. The memoryFS is, of course, mainly used *for* testing...

**Comment by mmccarty** [comment]
@martindurant Ryan is on my team. I want to use this issue as a pathfinder for getting us into Intake more formally. That will mean a PR will take a bit longer, but I think its worth it. Are you okay with that?

**Comment by martindurant** [comment]
Certainly!

**Comment by martindurant** [comment]
This has been fixed, closing for cleanup.
