### ISSUE TITLE
Created / modified timestamps?

### ISSUE THREAD

**Issue by limx0** [intake/filesystem_spec#265]
Is there a plan to add/support created/modified timestamps within fsspec? Are there any (known) reasons this could not be implemented?

**Comment by martindurant** [comment]
The local FS does have these:
```
In [2]: fs = fsspec.filesystem('file')
In [4]: fs.info('README.md')
Out[4]:
{'name': '/Users/mdurant/code/intake-examples/data_package/README.md',
 'size': 5477,
 'type': 'file',
 'created': 1585859007.1338813,
 'mode': 33188,
 'uid': 501,
 'gid': 20,
 'mtime': 1585859007.1310058}
```

Other filesystems do not necessarily provide this information, so there's nothing fsspec can do about that.

**Comment by limx0** [comment]
Thanks for the prompt response @martindurant. Agreed they do not exist on all filesystems - but many do (or could) implement them. I really like the common interface that fsspec strives to build, and I think having a shared method to access the created/modified time fits that goal.

I'm currently having trouble with local vs s3 filesystems, both have their own modified time in `info`, I would simply like to see a standardised method (and return type) for this data. The `local` fs seems to use an epoch timestamp while `s3fs` returns a datetime.   

Is this something you're open to? Happy to PR something if you are.

**Comment by martindurant** [comment]
I see what you mean. Currently, only name, type and size are guaranteed and uniform keys in the dict returned by info/ls, but we do also have some specific helpers like `size()` and `ukey()`. I would not be opposed to created/modified either as methods or keys in the info/ls dict, but of course, all backends would need updating. `fsspec` has very minimal dependencies, though, so I'm not sure how you would go about converting between the various formats you might see.

**Comment by martindurant** [comment]
`datetime.datetime.fromtimestamp(1585859007.1338813)` works for the unix timestamp given by localfs

**Comment by martindurant** [comment]
(on posix!)

**Comment by limx0** [comment]
> `datetime.datetime.fromtimestamp(1585859007.1338813)` works for the unix timestamp given by localfs

Yep this is exactly what I was planning to do. 

>`fsspec` has very minimal dependencies, though, so I'm not sure how you would go about converting between the various formats you might see.
I could well be wrong, but won't most would fall into either string, epoch or datetime? I would think we should be able to cover most bases with stdlib.

I'm happy to have a crack at the fsspec implementations & s3fs - and the other backends can implement as required? I'll make a start and see where I get to.

**Comment by limx0** [comment]
Thank you @martindurant
