### ISSUE TITLE
setting up a 'filecache' file system to access data from DigitalOcean spaces

### ISSUE THREAD

**Issue by martibosch** [intake/filesystem_spec#272]
Hello,
I am trying to set up a file system that opens `nc` files with xarray from my DigitalOcean spaces bucket and caches them locally.

In order to make fsspec compatible with DigitalOcean, I do the following:

```python
from os import environ

import boto3
import fsspec

session = boto3.Session(
    profile_name=environ.get('S3_PROFILE_NAME')
)
```

so that when I set up a regular s3 file system, e.g.:

```python
fs = fsspec.filesystem(
    's3',
    session=session._session,
    client_kwargs={'endpoint_url': environ.get('S3_ENDPOINT_URL')},
    cache_storage='foo',
)
fs.ls('my-bucket-name')
```

I obtain something like:

```
['my-bucket-name/my-dir-1',
 'my-bucket-name/my-dir-2',
 'my-bucket-name/my-dir-3',
 'my-bucket-name/my-dir-4',
 'my-bucket-name/my-dir-5',
 'my-bucket-name/my-dir-6',
 'my-bucket-name/my-dir-7',
 'my-bucket-name/my-dir-8',
 'my-bucket-name/my-dir-9',
 'my-bucket-name/my-dir-10',
 'my-bucket-name/my-dir-11',
 'my-bucket-name/my-dir-12',
 'my-bucket-name/my-dir-13']
```

and I can use `fs.open` and successfully open the remote files. Nevertheless, if I try to set up a local cache for my remote s3 as in:

```python
fs = fsspec.filesystem(
    'filecache',
    target_protocol='s3',
    session=session._session,
    client_kwargs={'endpoint_url': environ.get('S3_ENDPOINT_URL')},
    cache_storage='foo',
)
fs.ls('my-bucket-name')
```

I then obtain something like:

```
['my-bucket-name/26',
 'my-bucket-name/29',
 'my-bucket-name/37',
 'my-bucket-name/4a',
 'my-bucket-name/5a',
 'my-bucket-name/61',
 'my-bucket-name/6e',
 'my-bucket-name/72',
 'my-bucket-name/ad',
 'my-bucket-name/b0',
 'my-bucket-name/b3',
 'my-bucket-name/ca',
 'my-bucket-name/e2',
 'my-bucket-name/e4',
 'my-bucket-name/f4',
 'my-bucket-name/f8']
```

and if I try to open a known path from my remote with `fs.open`, I get a `FileNotFoundError`.

What am I doing wrong? I am sorry to bother you but I have not been able to find many documentation about this.

Thank you in advance,
Martí

**Comment by martindurant** [comment]
Note: in the latest version of s3fs, you should be passing a botocore session, not a boto3 one - this was done to achieve compatability with aiobotocore.

I am not entirely sure what that output of `ls` might mean...

In the call to "filecache", all the extra options should go into a `target_options=` dict, because some arguments are to the caching layer itself, some to go through to s3. This would look like
```
fs = fsspec.filesystem(
    'filecache',
    target_protocol='s3',
    target_options=dict(session=session._session,
        client_kwargs={'endpoint_url': environ.get('S3_ENDPOINT_URL')},
        cache_storage='foo')
)
```

However if you are using `open` or `open_files`, you can also do
```
of = fsspec.open("filecache::s3::/my-bucket-name/my-dir-*/*
    s3=dict(session=botocore_session,
        client_kwargs={'endpoint_url': environ.get('S3_ENDPOINT_URL')},
        cache_storage='foo')
)
```
where the sets of arguments are keyed by the protocol name.

btw: why is it better for you to pass a session instance around rather than pass the profile?

**Comment by martibosch** [comment]
thank you for your quick response.

I have amended my code to:

```
fs = fsspec.filesystem(
    'filecache',
    target_protocol='s3',
    target_options=dict(
        profile=environ.get('S3_PROFILE_NAME'),
        client_kwargs={'endpoint_url': environ.get('S3_ENDPOINT_URL')}
    ),
    cache_storage='foo'
)
```

and now I can successfully browse my bucket. Nonetheless, I am trying to open the files inside a function, to which I pass the `fs` from the snippet above as argument, and does the following:

```python
    ...
    with fs.open(file_key) as file_obj:
        if open_kws is None:
            open_kws = {}
        ds = xr.open_dataset(file_obj, **open_kws)
    ...
```

So when I call such function, the dataset is opened and the file is downloaded to the cache directory `foo`, yet I get the following error:

```python
Truncated Traceback (Use C-c C-$ to view full TB):
~/anaconda3/envs/my-env/lib/python3.7/site-packages/fsspec/implementations/cached.py in save_cache(self)
    147         with open(fn2, "wb") as f:
    148             pickle.dump(cache, f)
--> 149         os.replace(fn2, fn)
    150 
    151     def _check_cache(self):

OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpdw9i_kcy' -> 'foo/cache'
```

The wierd part is that a file does appear in the cache directory `foo`, and if I try to open it as in:

```python
ds = xr.open_dataset('foo/dcc7e4f0c11171a082751733cccbc20d162e3d54fd2d0a2d8e5806b383060771')
```

the dataset is loaded correctly. Yet if I use `fs.open(file_key)`, the file is downloaded again and I get the same `OSError`.

By the way: I was passing `session._session`, which corresponds to the botocore session, and I was doing so because:

```python
fs = fsspec.filesystem(
    's3',
    profile_name=environ.get('S3_PROFILE_NAME'),
    # session=session._session,
    client_kwargs={'endpoint_url': environ.get('S3_ENDPOINT_URL')},
)
```

raised the following:

```python
Truncated Traceback (Use C-c C-$ to view full TB):
~/anaconda3/envs/my-env/lib/python3.7/site-packages/s3fs/core.py in connect(self, refresh)
    278 
    279         if not self.passed_in_session:
--> 280             self.session = botocore.session.Session(**self.kwargs)
    281 
    282         logger.debug("Setting up s3fs instance")

TypeError: __init__() got an unexpected keyword argument 'profile_name'
```

but I have realized now that changing the keyword argument name to `profile` fixes it. I guess the mistake came because I was using `s3fs` before and `profile_name` is the keyword argument that I was passing to `s3fs.S3FileSystem`.

**Comment by martindurant** [comment]
Hm, we seem to be assuming that the location of temporary files and the cache you are writing are on the same file-system. `os.replace` doesn't say that this is a necessary precondition. The code could be changed to put the temporary file in the same directory with a random-generated name.

As a workaround, you could use "simplecache" instead, which doesn't store metadata at all.

**Comment by martibosch** [comment]
I have got it working by simply replacing 'filecache' for 'simplecache'. This should be enough for my purposes.

Thank you for your help!
