### ISSUE TITLE
Chained filesystem instance

### ISSUE THREAD

**Issue by ian-r-rose** [intake/filesystem_spec#274]
I like the new filesystem chaining syntax. Should I expect to be able to instantiate a filesystem through the registry using something like
```python
fs = fsspec.filesystem("filecache::s3")
```
?

I somewhat expected that to work, but as it stands I can only create an instance more directly:
```python
fs = fsspec.implementations.cached.WholeFileCacheFileSystem(
    target_protocol="s3",
    cache_storage="/tmp/"
)
```

**Comment by martindurant** [comment]
It isn't possible now, but it's certainly a good idea!
All the parts are around, so should be easy to implement.

**Comment by martindurant** [comment]
Sort of accidentally, `fsspec.core.url_to_fs` does exactly what you want
```
fs, _ = fsspec.core.url_to_fs("simplecache::s3://")
```
(I think the "://" is required)

I suppose this should be accessible directly under or replace `fsspec.filesystem` (which is simpler).

**Comment by martindurant** [comment]
Closing as implemented
