### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by impredicative** [intake/filesystem_spec#276]
The [changelog](https://filesystem-spec.readthedocs.io/en/latest/changelog.html) doesn't have updates for versions since 0.7.5. Why is this? Can it be updated?

**Comment by martindurant** [comment]
Good idea! I personally have been on various different projects and just didn't have the time to write these. I am currently going through the documentation to make things match the reality of the code.

**Comment by mivade** [comment]
Looks like 0.8.0 is also not recorded in the changelog. I found this after some things broke and was hoping to look there for some hints about what changed.

**Comment by martindurant** [comment]
We have not been particularly diligent about updating the changelog - this is still a rapidly moving codebase.

**Comment by martindurant** [comment]
Would you be interested in implementing tooling to update a changelog from merged PRs upon pushing a new release tag? I believe this can be fully automated (but of course not a complete replacement for a diff).

**Comment by impredicative** [comment]
> Would you be interested in implementing tooling to update a changelog from merged PRs upon pushing a new release tag? I believe this can be fully automated (but of course not a complete replacement for a diff).

No, that would have too much noise. It is the author's/maintainer's responsibility to maintain a concise human-friendly changelog. As it stands, there is no current changelog which is quite unprofessional for a package.

**Comment by TomAugspurger** [comment]
As a stopgap, is anyone able to go through the git history and write up a changelog for the last couple releases? @impredicative perhaps?

**Comment by impredicative** [comment]
@martindurant I don't understand why I and others have to keep asking for a changelog. Why is it difficult to have one? The longer it's ignored, the harder it gets to write. The published [changelog](https://filesystem-spec.readthedocs.io/en/latest/changelog.html) is currently missing entries for v0.8.6 and v0.8.7. Why even release without it? It's poor practice and is frustrating.
