### ISSUE TITLE
numpy slice assignment failing on `readinto`

### ISSUE THREAD

**Issue by JacksonMaxfield** [intake/filesystem_spec#277]
`readinto` failing to perform slice assignment:

```
~/active/cell/filesystem_spec/fsspec/spec.py in readinto(self, b)
   1249         # for i in range(len(data)):
   1250         #     b[i] = data[i]
-> 1251         b[: len(data)] = data
   1252         return len(data)
   1253 

ValueError: invalid literal for int() with base 10: ''
```

**`fsspec` version:** 0.7.2

**Context:**
I am one of the developers for [`aicsimageio`](https://github.com/AllenCellModeling/aicsimageio), relevant to this issue is the fact that we use delayed dask arrays to read microscopy images, but as a part of that we support very large files (usually this means >200GB). We natively support handing in `str` and `Path` to the `AICSImage` object as one would expect and I was in the process of extending support to reading from `S3File` or really, _any_ `fsspec` file like object.

Bear with me...
**Commands for reproduction setup:**
```bash
git clone git@github.com:AllenCellModeling/aicsimageio.git
cd aicsimageio
git checkout feature/support-s3-file
pip install -e .
python
```

(The above was done in a conda environment on python 3.7)

**Commands to reproduce:**
```python
from aicsimageio import AICSImage
from s3fs import S3File, S3FileSystem
fs = S3FileSystem(anon=True)
f = S3File(fs, "allencell/aics/pipeline_integrated_single_cell/cell_images_3d/00001bb5_16872_35317_reg.tiff")
img = AICSImage(f)
print(img.shape)
```

**Traceback:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maxfield/active/cell/aicsimageio/aicsimageio/aics_image.py", line 207, in shape
    return self.size()
  File "/home/maxfield/active/cell/aicsimageio/aicsimageio/aics_image.py", line 197, in size
    return tuple([self.dask_data.shape[self.dims.index(dim)] for dim in dims])
  File "/home/maxfield/active/cell/aicsimageio/aicsimageio/aics_image.py", line 197, in <listcomp>
    return tuple([self.dask_data.shape[self.dims.index(dim)] for dim in dims])
  File "/home/maxfield/active/cell/aicsimageio/aicsimageio/aics_image.py", line 152, in dask_data
    reader_data = self.reader.dask_data
  File "/home/maxfield/active/cell/aicsimageio/aicsimageio/readers/tiff_reader.py", line 176, in dask_data
    self._dask_data = self._construct_dask_array(self._file, tiff)
  File "/home/maxfield/active/cell/aicsimageio/aicsimageio/readers/tiff_reader.py", line 128, in _construct_dask_array
    sample = scenes[0].pages[0].asarray()
  File "/home/maxfield/miniconda3/envs/aicsimageio-test/lib/python3.7/site-packages/tifffile/tifffile.py", line 4587, in asarray
    out=out
  File "/home/maxfield/miniconda3/envs/aicsimageio-test/lib/python3.7/site-packages/tifffile/tifffile.py", line 6400, in read_array
    n = fh.readinto(result)
  File "/home/maxfield/miniconda3/envs/aicsimageio-test/lib/python3.7/site-packages/fsspec/spec.py", line 1241, in readinto
    b[: len(data)] = data
ValueError: invalid literal for int() with base 10: ''
```

**Comments:**
From some debugging, if we ignore all the `aicsimageio` reader code, the ultimate error that occurs occurs during the slice assignment in `readinto`. This same file, which can be downloaded [here](https://open.quiltdata.com/b/allencell/tree/aics/pipeline_integrated_single_cell/cell_images_3d/00001bb5_16872_35317_reg.tiff), (or with any other S3 downloader), can be read in to `AICSImage` just fine as a `str` or `Path` so it seems to be this slice assignment operation. I found what I would consider a really weird (and not optimal) but working solution of replacing the slice assignment with a simple loop and single item assignment: [link](https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L1243)
```python
def readinto(self, b):
    """mirrors builtin file's readinto method

    https://docs.python.org/3/library/io.html#io.RawIOBase.readinto
    """
    data = self.read(len(b))
    for i in range(len(data)):
        b[i] = data[i]
    # b[: len(data)] = data
    return len(data)
```

Which I will be opening a PR with for feedback on how to solve the issue in a more optimized fashion.

Using the loop above, the above image reading code now works:
```python
from aicsimageio import AICSImage
from s3fs import S3File, S3FileSystem
fs = S3FileSystem(anon=True)
f = S3File(fs, "allencell/aics/pipeline_integrated_single_cell/cell_images_3d/00001bb5_16872_35317_reg.tiff")
img = AICSImage(f)
print(img.shape)
```
`(1, 1, 6, 64, 168, 104)`

**Comment by martindurant** [comment]
Is the length of the data zero here by any chance?
`readinto` is designed to work with bytearrays and buffers/memoryviews. I suppose in your case the assignee is a numpy array, so maybe all inputs should be wrapped in a memoryview?

```
def readinto(self, b):
    """mirrors builtin file's readinto method

    https://docs.python.org/3/library/io.html#io.RawIOBase.readinto
    """
    data = self.read(len(b))
    memoryview(b)[: len(data)] = data
    return len(data)

**Comment by martindurant** [comment]
or `memoryview(b).cast("B")[: len(data)] = data`

**Comment by JacksonMaxfield** [comment]
TIL, `memoryview`

Both suggestions work!

To answer the question of what is in the `data`:
***type:*** `bytes`
***content:*** a whole bunch of `\x00` (literally nothing else)
***length:*** 17472

**Comment by martindurant** [comment]
I recommend you use the latter suggestion in your PR. I suppose your numpy data type already uint8 (which is normal for images), but you need the cast for other cases where filling in the *binary* contents of a numpy array with any other type

I'd also appreciate a test showing that this works. The roundtrip would be something like
```
arr = numpy.arange(10, dtype=dt
arr.tofile(temporary_file)
arr2 = np.empty_like(arr)
 with fsspec.open('temp', 'rb') as f:
     f.readinto(arr2)
assert (arr == arr2).all()
```
which I would check for dt= 'uint8', 'int8', 'int32', 'float64'

> a whole bunch of `\x00`

(might have been optimizable... :) )

**Comment by JacksonMaxfield** [comment]
Thanks! PR updated with tests. Sorry for not knowing too much about how to test this stuff. Appreciate the input :)
