### ISSUE TITLE
LocalFileSystem.glob does not pass kwargs to super().glob

### ISSUE THREAD

**Issue by masda70** [intake/filesystem_spec#283]
I want to pass `detail=True` to `LocalFileSystem.glob`, but this is not currently possible. I think simply passing **kwargs to `super().glob` would suffice.

https://github.com/intake/filesystem_spec/blob/4decaca5ef743e5065aa9350d79e78547999b9a2/fsspec/implementations/local.py#L52

**Comment by martindurant** [comment]
Sure, sounds reasonable. Do you intend to submit this with a test?

**Comment by martindurant** [comment]
ping @masda70

**Comment by masda70** [comment]
Hi Martin, thank you for bumping this thread. Finally found some time to propose a PR. I hope it is up to your standards.

https://github.com/intake/filesystem_spec/pull/344

**Comment by TomAugspurger** [comment]
Closed by #344
