### ISSUE TITLE
Provide an explicit way to register a protocol

### ISSUE THREAD

**Issue by tebeka** [intake/filesystem_spec#293]
I'm working on a [v3io driver](https://github.com/v3io/v3io-fs) for fsspec.
I can't find a way to register the `v3io` protocol, currently I'm doing
```python
from fsspec.registry import known_implementations

known_implementations[V3ioFS.protocol] = {
     'class': 'v3iofs.V3ioFS',
}
```

Which is  seems like working with internal implementaion detilas.

I suggest adding `register_protocol(protocol: str, cls: type)` function that will allow implementations to register their protocol. I should probably raise an error if the protocol is already registered.

**Comment by martindurant** [comment]
I agree there should be such a function in the top level, to stop having to interact directly with the known_protocols - although this dict is supposed to be accessed *before* the target package is imported. So far, it has been edited only using PRs to this repo.

We should probably follow the pattern of drivers for intake, and use entrypoints: so that you can tell that a package claims to have an implementation, but only import it upon request.

**Comment by martindurant** [comment]
The similar function in intake: https://github.com/intake/intake/blob/master/intake/source/__init__.py#L18

**Comment by martindurant** [comment]
By the way, have you considered any overlap there may be between iguazio and [intake](https://intake.readthedocs.io/en/latest/) ?

**Comment by tebeka** [comment]
What do you mean by `overlap`?

**Comment by martindurant** [comment]
I mean, that Intake is concerned with describing arbitrary datasets and their metadata in a simple and extensible way, and how to form them into catalogs for local and remote loading; iguazio is concerned in more depth and specialisation with data science/AI pipelines, including how to transform from one data set to another, build and use models and provenance. It seems to me that the two share some things in common, with very different emphasis, so there may be some scope for collaboration. For example, if you find it useful to use the fsspec formalism for storage, then you might also find it useful to list training data or fitted models using an Intake catalog.

**Comment by tebeka** [comment]
Sorry for the late addition. But IMO it should be OK to register the same class with the same name,
e.g. the below should be OK
```python
fsspec.registry.register_implementation('v3io', V3ioFS)
fsspec.registry.register_implementation('v3io', V3ioFS)
```
The reasoning is that people will call `register_implementation` when module is imported, and in some cases this code can run twice.

**Comment by martindurant** [comment]
I'm afraid that missed the cut - but please add it in a new PR if you really face the situation. I would have thought it unlikely that code is executed twice during import, but you can always specify that clobber is OK.

**Comment by tebeka** [comment]
OK, I'll have it run as-is and if there are problems will open a new issue. Thanks

**Comment by chanhosuh** [comment]
@martindurant a small thing, but shouldn't `__all__` in `fsspec.registry` include 'register_implementation`?

**Comment by martindurant** [comment]
@chanhosuh , yes, that would be reasonable (although it is imported in `__init__` anyway)
