### ISSUE TITLE
open and filesystem.open don't match 

### ISSUE THREAD

**Issue by limx0** [intake/filesystem_spec#303]
Hi, 

I kept hitting a `TypeError: 'LocalFileOpener' object is not iterable` when trying to iterate over the lines in a file when I came across the fact that `open` and `filesystem.open` don't seem to match. 
Simple example:

```python
# Write some test data
with open('test.txt', 'wb') as f:
    f.writelines([b'a\n', b'b\n', b'c\n'])

# Open with filesystem.open, works as expected
of = fsspec.filesystem('file').open('file://test.txt')
with of as f:
    for line in f:
        print(line)

# Open with `open`, throws a TypeError: 'LocalFileOpener' object is not iterable
of = fsspec.open('file://test.txt')
with of as f:
    for line in f:
        print(line)
```

Is this expected? I've been iterating over lines with the memory and s3fs filesystems without issue

**Comment by martindurant** [comment]
It is interesting, because if you were to look, you would find that `f.__iter__` does indeed exist. However, it seems that it needs to exist on the class, not the instance. I have posted the fix.

**Comment by limx0** [comment]
I did see that, but also didn't notice anything obviously wrong - Nice find and thanks for the quick fix @martindurant !
