### ISSUE TITLE
Pickling OpenFile object ignores newline attribute

### ISSUE THREAD

**Issue by mgsdk** [intake/filesystem_spec#318]
When pickling `OpenFile` objects, the `newline` attribute is not persisted. This causes issues on Windows, where a value of `None` inserts an additional `\r` when using the file with a stream already containing correct line termination.

```python
import fsspec
import pickle


def main():
    test = fsspec.open(__file__, newline=b"")
    
    pickled = pickle.dumps(test)
    restored = pickle.loads(pickled)
    
    assert test.newline == restored.newline
    return


if __name__ == '__main__':
    main()
```

Is there an underlying reason as to why this is not pickled, or was it simply missed during the addition of the `newline` attribute?

**Comment by TomAugspurger** [comment]
Thanks for the report. I assume this is related to https://github.com/dask/dask/issues/6313?

**Comment by mgsdk** [comment]
Yes, adding the `newline` to the attributes being pickled solves the issue for me locally. Was curious if there was a reason for it not being included by default, or of it was an oversight.

**Comment by martindurant** [comment]
This is definitely an omission
