### ISSUE TITLE
Clearing the cache / Question 1/2

### ISSUE THREAD

**Issue by gmaze** [intake/filesystem_spec#324]
Hi folks !

This is 1/2 questions wrt to fsspec cache handling when we want to clear it.

## Context:
I develop a python library to work with ocean data collected using a specific type of instruments (Argo floats): https://github.com/euroargodev/argopy
Data can be fetched from local files or from an erddap server online.

I recently tried to use fsspec to implement file/resource management and ease handling of cached data.
I ended up wrapping ``file``, ``memory`` and ``http`` fsspec file systems into [classes](https://github.com/euroargodev/argopy/blob/master/argopy/stores/fsspec_wrappers.py) that managed custom methods like open_dataset or open_dataframe.

## Question 1:
When my users specify to use a caching system, I simply wrap the original one with a ``filecache``.
I wanted to offer the possibility for users to clean up the cache from data they would have fetched, but I couldn't figure how fsspec allows to do this.

I found the [clear_instance_cache()](https://filesystem-spec.readthedocs.io/en/latest/api.html?highlight=clear%20cache#fsspec.spec.AbstractFileSystem.clear_instance_cache) but I don't really understand what it is doing. In any case, when I call on it, it doesn't trigger some deletion in the cache folder files and registry (the pickle ``cache`` file):

```python
import fsspec
import os

# Create a dummy file, read it with fsspec, and check that the cache folder is filled:
with open("dummy_file.txt", "w") as fp:
    fp.write('Hello world!')

fs = fsspec.filesystem("filecache", target_protocol="file", target_options={'simple_links': True}, cache_storage="./tmp")

with fs.open("dummy_file.txt", "r") as fp:
    txt = fp.read()

print("File is cached:\n", os.listdir("./tmp"))

# Now, try to clear the cache:
fs.clear_instance_cache()

# and check again the cache folder:
print("Expect cache folder to be cleared:\n", os.listdir("./tmp"))
```
which produces:
```
File is cached:
 ['cache', '0515f6cf660c690fd787b4d6d305b8ec11d894cdb5cacf6fee8aeff541de3eac']
Cache should be cleared:
 ['cache', '0515f6cf660c690fd787b4d6d305b8ec11d894cdb5cacf6fee8aeff541de3eac']
```

I expected that the cache folder ``./tmp`` would be empty, or removed after the ``clear_instance_cache()`` call.

**Do you have any idea of what am I doing wrong here ? 
Could you please help me understand the behavior of the ``clear_instance_cache`` method ?**

**Comment by martindurant** [comment]
`fs.clear_instance_cache()` is not the method you want. It refers to a cache of instances of the filesystem, such that if you were to call the constructor again with the same arguments, you get the same instance  back instead of a new one. This helps with sharing resources, not having to reconnect to remote services. There is *also* a cache of directory listings, so many similar names.

There is actually *no functionality* for clearing the cache. There should be! For now, you could clear the metadata with `fs.cached_files[-1].clear(); fs.save_cache()`, which will cause reloads of files, but not delete existing ones. Deleting the "cache" files should have the same effect. Also, deleting the files from the cache should work too, something in the metadata but not on disc should cause a reload, but I think now would cause an exception.

**Comment by gmaze** [comment]
Thanks for these explanations !
I now understand better the ``clear_instance_cache()``
About the alternative you suggest, I'm afraid they would simply clear the cache content, `whatever` the file system that created them. So in the case where a single folder is being used by more than one fs, this could remove content that should not. Is this correct ?

**Comment by martindurant** [comment]
Yes, my example would clear all the cache from the target folder. You want a per-instance cache, but sharing the same location? That might be trickier; you can keep the current state in memory (instead of a file), but you wouldn't know what other instances/processes are doing to the cache, then.

**Comment by gmaze** [comment]
yes, that's why I tried to implement a `registry` in the wrapper I created, more here: #325 
would that be a good approach ?

**Comment by gmaze** [comment]
I'm closing this issue since it's be resolved in our library using a registry
