### ISSUE TITLE
local filesystem isn't consistent

### ISSUE THREAD

**Issue by pvanderlinden** [intake/filesystem_spec#326]
- If you set `auto_mkdir` to True for a local filesystem, it won't actually listen to this, for example when copying files, it just invokes `shutil.copyfile`
- if you pass an uri with the scheme included in it to certain functions, the local filesystem will give an error.

**Comment by martindurant** [comment]
`auto_mkdir` is only used by `open`. You are right that it would be reasonable to expect it to matter for `cp` too.

**Comment by martindurant** [comment]
This is of course easy to fix and ideally both points can be covered by tests. The method `._strip_protocol` deals with removing the protocol, and in the local file case, also makes it posixy.

**Comment by pvanderlinden** [comment]
I think my main issue is that I try to use the local filesystem as a drop in replacement to test a few things which now uses gcsfs, and I was expecting the implementation to mostly behave similar.

**Comment by martindurant** [comment]
There are many methods to get through, and many tests still to write :)
Would you like to contribute the fixes for the two cases here?

**Comment by pvanderlinden** [comment]
I'm not sure if I have the time for the fixes soon to be honest.

**Comment by pvanderlinden** [comment]
I might have to though, as I won't be able to finish this without the fixes.

**Comment by pvanderlinden** [comment]
Thanks @martindurant for the quick fix!
