### ISSUE TITLE
URL Unpacking does not work as expected when chaining 3(+) FileSystems

### ISSUE THREAD

**Issue by sodre** [intake/filesystem_spec#334]
Currently URL unpacking expects the following syntax if we want to open a zip file stored in S3 with a blockcache in the middle. The use case in question is a 19GB file for the Coco dataset.

This is the syntax that works:

> of = fsspec.open_files("zip://**.jpg::blockcache://fast-ai-coco/unlabeled2017.zip::s3://", s3={"anon":True}) 

Shouldn't this be:

> of = fsspec.open_files("zip://**.jpg::blockcache::s3://fast-ai-coco/unlabeled2017.zip", s3={"anon":True})

_Originally posted by @martindurant in https://github.com/intake/filesystem_spec/pull/332#issuecomment-648167709_

**Comment by martindurant** [comment]
I wonder if you could make an example with fewer stages and only local files (so we can include in tests). 
Do you see the problem with a urls like
- "zip://*::simplecache::file://localfile.zip"
- "zip://inner_file::simplecache::file://localfile.zip"
- "zip://*::simplecache://::file://localfile.zip"

**Comment by sodre** [comment]
I will take a look at creating the test case later tonight.

**Comment by martindurant** [comment]
This can be closed?
