### ISSUE TITLE
MemoryFileSystem fails to rewind

### ISSUE THREAD

**Issue by joachimvalente** [intake/filesystem_spec#349]
# Steps to reproduce

```py
>>> import fsspec
>>> fsspec.__version__
0.7.4
>>> fs = fsspec.filesystem("memory")
>>> with fs.open("foo", "w") as f:
...   f.write("bar")
>>> with fs.open("foo") as f:
...   print(f.read())
b''
>>> with fs.open("foo") as f:
...   f.seek(0) # we shouldn't need this!
...   print(f.read())
b'bar'
```

# Root cause

This is due to this line:

https://github.com/intake/filesystem_spec/blob/0e201d4321ae27bc1ac37d4b28057d085de393f1/fsspec/implementations/memory.py#L179-L180

# Partial fix

It works if we comment out that line, or if we do `.seek(0)` instead of `.seek(0, 2)`. I'm guessing we want something like this:

https://github.com/intake/filesystem_spec/blob/0e201d4321ae27bc1ac37d4b28057d085de393f1/fsspec/implementations/memory.py#L117-L120

... except that we don't have access to `mode` in `__exit__`, so we'd have to save it in `_open`?

**Comment by martindurant** [comment]
How about
```
def close(self): 
    self.size = self.seek(0, 2) 
    self.seek(0)
```
although this could be done better at open time, e.g., unindent the [last line](https://github.com/intake/filesystem_spec/blob/0e201d4321ae27bc1ac37d4b28057d085de393f1/fsspec/implementations/memory.py#L174) of init. Note that there is an implicit assumption that a file is opened in at most one place at a time.

**Comment by martindurant** [comment]
(actually, just use the first option - init is not called again on reading)

**Comment by joachimvalente** [comment]
Ah nice! Thanks for your answer. I can send you a PR.

Two questions though:

* why is `close` even called at this point? I can't figure out why `close` or `__exit__` would be called before leaving the entire `with` block
* do we not want to keep `seek(0, 2)` for append mode? if so, we'd probably want to save the mode somewhere in `_open` so we can read it back here in `close`

**Comment by martindurant** [comment]
Close happens when leaving the with-context. It's not a real close, in the sense of BytesIO (the data remains accessible), but we need to get the size of the data, so that a read mode access will know that value. `seek(0, 2)` is needed to a) get the size or b) set the location for append mode. The instance doesn't actually have a write, read or append mode, it's always effectively "r+". This argues that the seek to start or end is actually something that should happen in MemoryFileSystem._open instead of anywhere within the file...
Perhaps it would be good to code up your example and some more as tests before trying to fix them! Would you like to make that PR.

**Comment by joachimvalente** [comment]
My question is that `close` seems to be called twice, and I'm not sure why. If it were just called when exiting the `with` block there would be no bug. But instead:

* after `__enter__` is run, `f.tell()` would return 0
* but then `close` is called, after `__enter__` but before `print(f.read())`
   https://gist.github.com/joachimvalente/99b56efa998af9f4fdd53f42e6b98312#file-bug-py-L144-L154
* then `print(f.read())` is called but since `seek(0, 2)` already happened, we're not reading anything
   https://gist.github.com/joachimvalente/99b56efa998af9f4fdd53f42e6b98312#file-bug-py-L155-L157
* and finally `close` is called again
   https://gist.github.com/joachimvalente/99b56efa998af9f4fdd53f42e6b98312#file-bug-py-L158-L169

**Comment by martindurant** [comment]
I think that's fine - whenever you open the file for reading, you get back the original instance, and you can close it as many times as you like without any harmful effect. The pdb log is quite hard to read...

**Comment by joachimvalente** [comment]
Thanks for the explanations. Just sent you a PR!
