### ISSUE TITLE
Iterating over local files

### ISSUE THREAD

**Issue by ifiddes** [intake/filesystem_spec#350]
I was expecting to be able to do this regardless of the file system being used:

```
with fsspec.open(file) as fh:
    for line in fh:
        print(line)
```

This works fine for S3FS, but for a local file, the returned `LocalFileOpener` object lacks the classic methods associated with an open file handle like `seek`, or a `__iter__`. However, the `fh.f`member, a `io.BufferedReader`, has the necessary functionality.

This makes writing an API that is meant to seamlessly treat local files and remote files the same way require a wrapper in front of `open`. Is there a reason for this?

**Comment by martindurant** [comment]
On current master, this seems to work fine (I think since 44f78aa28b13f572a3e579611fe39e29135ee86a ). Can you try?

Note that the default open mode is 'rb' (i.e., binary), so you might want to specify 'rt'.

**Comment by ifiddes** [comment]
Ah, it seems like I have to open in `rt` to get an iterable. It does seem like this is a bit funky of a return signature, though:

```
with fsspec.open(myfile, 'rt') as fh:
    assert False, type(fh)
```

```>>>AssertionError: <class '_io.TextIOWrapper'>```

```
with fsspec.open(myfile, 'rb') as fh:
    assert False, type(fh)
```

```>>>AssertionError: <class 'fsspec.implementations.local.LocalFileOpener'>```

**Comment by martindurant** [comment]
The return type of `fsspec.open` is always an `OpenFile` instance; when you enter the context, the get the appropriate file-like object. Note that the standard python `open` also returns different types, depending on whether you use text or binary mode.
LocalFileOpener maybe could be simpler/clearer. I you can think of a way to do this, please let me know!
