### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by sodre** [intake/filesystem_spec#359]
@martindurant, are we close to a new release of fssspec? 

In particular I am looking for the fixes to #329, and #332, and #334 to be available in conda-forge and PyPi.

**Comment by martindurant** [comment]
I intend to release fsspec, gcsfs and s3fs together in the near future. fsspec could come earlier, I suppose.

**Comment by sodre** [comment]
thank you!

**Comment by martindurant** [comment]
Released v0.8.0
