### ISSUE TITLE
ENH: can given URL/filesystem can return a local path

### ISSUE THREAD

**Issue by aaronspring** [intake/filesystem_spec#360]
bool whether `"*cache://"` in urlpath 

came up in https://github.com/intake/intake_geopandas/pull/16 https://github.com/intake/intake_geopandas/pull/17

**Comment by martindurant** [comment]
Thanks for bringing this up.

That's probably not the right test
A failing case (never mind "::" versus "://"):
- "zip://myfile::simplecache::s3://bucket/file.zip"

I think the caching and local filesystems should have a class attribute that marks them as returning local files. In this case, the filesystem instance would be zip, and not have the attribute set.
