### ISSUE TITLE
dependency on aiohttp should be in the requirements.txt

### ISSUE THREAD

**Issue by bmccandless** [intake/filesystem_spec#366]
the update to 0.8.0 brings in a dependency to aiohttp, which is not listed in the requirements.   
I therefore get an import error when using fsspec.

**Comment by juarezr** [comment]
I have the same error while [building](https://github.com/petl-developers/petl/pull/507) for [python3.6](https://travis-ci.org/github/petl-developers/petl/jobs/714909092#L1221) and [python3.7](https://travis-ci.org/github/petl-developers/petl/jobs/714909093#L1363).

Any chance of including `aiohttp` as dependecy or maybe a import check as workaround?

Thanks

**Comment by martindurant** [comment]
fsspec does *not* depend on aiohttp, only the HTTP backend does. Attempting to use the HTTP backend without it should display `'HTTPFileSystem requires "requests" and "aiohttp" to be installed'` (on master).

**Comment by juarezr** [comment]
Understood.

Although I fixed my build, other environments relying in `fsspec` + `requests` installed but without `aiohttp` could break.

This configures a serious issue that needs fixing here?

**Comment by mivade** [comment]
I actually get the following error when running tests of a project with 0.8.0:

```
ImportError: HTTPFileSystem requires "requests" to be installed
```

However looking at the full traceback what is actually happening is this:

```
ModuleNotFoundError: No module named 'aiohttp'
```

so something is clearly off and it looks like `aiohttp` *is* actually required for HTTP support but we get an error message that hides this fact.

**Comment by martindurant** [comment]
The message is fixed on master https://github.com/intake/filesystem_spec/blob/master/fsspec/registry.py#L100

**Comment by mivade** [comment]
Glancing at `setup.py`, it wouldn't be a bad idea to use "extras" to make it easier to get these dependencies by doing something like `pip install fsspec[http]`. I can put together a PR for this shortly.

**Comment by martindurant** [comment]
Good idea. Obviously there are quite a few... I wonder if it could be done in a way not to repeat the information in registry.py . 
(Indeed, it would be good to implement #206 , which is tangentially related)
