### ISSUE TITLE
Zarr dataset on requester pays bucket only opening if I list the files first!?

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/filesystem_spec#386]
@martindurant , this is pretty bizarre: I have a notebook that used to open a zarr dataset (requester pays bucket), but after upgrading my environment, opening the dataset no longer works unless I list the files first!?  

So this doesn't work:
```python
xr.open_zarr(fsspec.get_mapper('s3://pangeo-data-uswest2/esip/adcirc/adcirc_01d', 
                                    anon=False, requester_pays=True))
```
but this does:
```python
fs = fsspec.filesystem('s3',anon=False, requester_pays=True)
fs.ls('s3://pangeo-data-uswest2/esip/adcirc/adcirc_01d/')
xr.open_zarr(fsspec.get_mapper('s3://pangeo-data-uswest2/esip/adcirc/adcirc_01d', 
                                    anon=False, requester_pays=True)
```

Here's the notebook: https://nbviewer.jupyter.org/github/rsignell-usgs/hurricane-ike-water-levels/blob/master/fsspec_strangeness.ipynb

I don't have a minimal test, but it should be reproducible on binder using this link: [![badge](https://img.shields.io/static/v1.svg?logo=Jupyter&label=Pangeo+Binder&message=AWS+us-west-2&color=orange)](https://aws-uswest2-binder.pangeo.io/v2/gh/rsignell-usgs/hurricane-ike-water-levels.git/zhdf?urlpath=git-pull?repo=https://github.com/rsignell-usgs/hurricane-ike-water-levels) and running the "fsspec_strangeness" notebook.

This is using `fsspec=0.8.0` and `xarray from master`.    I guess this could also be an xarray issue?  
I have no idea.   😕 
But I bet you do.  😄

**Comment by martindurant** [comment]
What is your version of s3fs?

**Comment by martindurant** [comment]
I suspect that the bucket has list_object permissions, but not get_object permissions. If the files have not already been listed (so their details are cached), s3fs uses headObject to get a particular key's info, which is why you see a difference in behaviour.

**Comment by ocefpaf** [comment]
Hi @martindurant, I'm trying to debug this too but I know nothing about S3 buckets. Not sure how to proceed here.

**Comment by rsignell-usgs** [comment]
@martindurant, but it must have access permission because I can read the zarr dataset, right?  Or perhaps (likely) I'm not understanding your reply.

We have `s3fs=0.5.0` here.

**Comment by martindurant** [comment]
See https://github.com/aio-libs/aiobotocore/issues/825 

You can try setting the environment variable AWS_DEFAULT_REGION as a workaround, or adding `client_kwargs={"default_region": ...}` into `get_mapper`

**Comment by rsignell-usgs** [comment]
I've probably got some syntax error? 
```
ds = xr.open_zarr(fsspec.get_mapper('s3://pangeo-data-uswest2/esip/adcirc/adcirc_01d', 
                                    anon=False, requester_pays=True, 
                                   client_kwargs={"default_region":'us-west-2'}))
```
returns
```
TypeError: _create_client() got an unexpected keyword argument 'default_region'
```

**Comment by martindurant** [comment]
Sorry, should be "region_name"

**Comment by rsignell-usgs** [comment]
Yep, thanks @martindurant !    It would be nice to not have to specify the region in `s3fs=0.5.0` (we didn't have to specify it in `s3fs=0.4.2`), but at least I don't need that goofy workaround of listing the files first.  So this works:

```python
ds = xr.open_zarr(fsspec.get_mapper('s3://pangeo-data-uswest2/esip/adcirc/adcirc_01d', 
                                    anon=False, requester_pays=True, 
                                   client_kwargs={'region_name:'us-west-2'}))
```

**Comment by martindurant** [comment]
Yep - this is something that aiobotocore needs to wort out for us - it would be good to chime in on that issue to give your specifics, to see if it can help them correct the problem.
https://github.com/aio-libs/aiobotocore/issues/825
