### ISSUE TITLE
Version 0.8.1 dropped support for Python 3.6

### ISSUE THREAD

**Issue by tsibley** [intake/filesystem_spec#402]
It appears this was accidental during a change intended to drop support for Python 3.5:

- Commit: https://github.com/intake/filesystem_spec/commit/21c43162d101d38f0f46ff2faaf057901d60d758
- Issue: https://github.com/intake/filesystem_spec/issues/368

The `python_requires` value is `>3.6` which excludes 3.6. I believe it wants to be `>=3.6`.

https://github.com/intake/filesystem_spec/blob/38e837cc5b647e351a2ae2e5a1b0f824bdaa96f9/setup.py#L33

The Trove classifiers still specify 3.6 support:

https://github.com/intake/filesystem_spec/blob/38e837cc5b647e351a2ae2e5a1b0f824bdaa96f9/setup.py#L20-L22

and automated testing still tests against 3.6:

https://github.com/intake/filesystem_spec/blob/38e837cc5b647e351a2ae2e5a1b0f824bdaa96f9/tox.ini#L3

If the change was _not_ accidental, then I'd like to advocate for keeping 3.6 support. :-)

**Comment by martindurant** [comment]
Hm, OK - we test, so clearly it works! Happy to have 36 back in the allowed python versions for the next release.

**Comment by tsibley** [comment]
Ok, so I was a little confused. I forgot that the Requires-Python spec `>3.6` excludes 3.6.0 but _allows_ 3.6.1 and higher. This is most likely a non-issue. The problem I was seeing in our environment appears to lie within other tooling (Pipenv, it seems), not the metadata fsspec declares. Sorry for the noise. :pray:
