### ISSUE TITLE
No changelog for 0.8.x

### ISSUE THREAD

**Issue by QuLogic** [intake/filesystem_spec#403]
The [changelog file](https://github.com/intake/filesystem_spec/blob/master/docs/source/changelog.rst) contains no changes for 0.8.0 or 0.8.1.

**Comment by impredicative** [comment]
@QuLogic There is already an open issue #276 for the changelog not being maintained. It's a chronic problem. I don't think we need a duplicate issue.

**Comment by QuLogic** [comment]
Yes, closing as a duplicate.
