### ISSUE TITLE
`_run_until_done` errors when `asyncio.current_task()` is None

### ISSUE THREAD

**Issue by ryanSoley** [intake/filesystem_spec#407]
I'm experimenting with the async S3 filesystem and running into a problem when trying to run synchronous commands with `asynchronous=True`. Specifically, I'm trying to run `_pipe_file` asynchronously and `pipe_file` synchronously with the same filesystem instance.

Awaiting the asynchronous `_pipe_file` works as expected. When calling the synchronous `pipe_file`, the `_run_until_done` function is raising the following error on `asyncio.tasks._unregister_task`.

The error occurred running off the master branch in a Jupyter notebook (hopefully it isn't Jupyter's event loop messing things up):

```python
import asyncio
import fsspec

fs = fsspec.filesystem("s3", asynchronous=True, loop=asyncio.get_running_loop())
await fs._connect()

await fs._pipe_file("path", b"data") # works as expected

fs.pipe_file("path", b"data") # throws the following error
```

```python
~/oss/filesystem_spec/fsspec/asyn.py in _run_until_done(coro)
     19     loop = asyncio.get_running_loop()
     20     task = asyncio.current_task()
---> 21     asyncio.tasks._unregister_task(task)
     22     current_task = asyncio.tasks._current_tasks.get(loop)
     23     assert task == current_task

~/miniconda3/envs/fsspec/lib/python3.7/_weakrefset.py in discard(self, item)
    112         if self._pending_removals:
    113             self._commit_removals()
--> 114         self.data.discard(ref(item))
    115
    116     def update(self, other):

TypeError: cannot create weak reference to 'NoneType' object
```

This appears to be due to the fact that `asyncio.current_task()` is returning None, which it fails to unregister. I patched `fsspec.asyn._run_until_done` with the following code in order to get the `pipe_file` call to run synchronously without errors (I only added the two `if task is not None` checks):

```python
def new_run_until_done(coro):
    loop = asyncio.get_running_loop()
    task = asyncio.current_task()

    if task is not None:
        asyncio.tasks._unregister_task(task)

    current_task = asyncio.tasks._current_tasks.get(loop)
    assert task == current_task

    if task is not None:
        del asyncio.tasks._current_tasks[loop]

    runner = loop.create_task(coro)
    while not runner.done():
        loop._run_once()

    asyncio.tasks._current_tasks[loop] = task
    return runner.result()

fsspec.asyn._run_until_done = new_run_until_done
```

I'm not familiar enough with `asyncio` to say whether or not this is a good or complete solution, so I wanted to discuss it before a PR.

**Comment by martindurant** [comment]
I think the expectation is, that when you call an instance marked as asynchronous=True, you do so only from within an async context. The following should work
```
async def runme():
    fs = fsspec.filesystem("s3", asynchronous=True, loop=asyncio.get_running_loop())
    await fs._connect()
    await fs._pipe_file("path", b"data") # works as expected
    fs.pipe_file("path", b"data")
```
