### ISSUE TITLE
Release 0.8.1 introduced python 3.6 asyncio incompatibility - module 'asyncio' has no attribute 'get_running_loop'

### ISSUE THREAD

**Issue by pschork** [intake/filesystem_spec#410]
```
File "/home/ubuntu/.virtualenvs/pipeline/lib/python3.6/site-packages/fsspec/asyn.py", line 19, in _run_until_done
{bash_operator.py:157} INFO -     loop = asyncio.get_running_loop()
{bash_operator.py:157} INFO - AttributeError: module 'asyncio' has no attribute 'get_running_loop'
```
This https://github.com/intake/filesystem_spec/commit/9f312ac3bbc9560ddeb9706e2754713af8ac01a2 change seems to have broken python 3.6 compatibility - `asyncio.get_running_loop()` requires python 3.7

If running python3.6 you can downgrade to [0.8.0](https://github.com/intake/filesystem_spec/releases/tag/0.8.0) as workaround.

**Comment by martindurant** [comment]
Seems we can replace with `get_event_loop`:

> Signature: asyncio.get_event_loop()
> Docstring:
> Return an asyncio event loop.
> 
> When called from a coroutine or a callback (e.g. scheduled with
> call_soon or similar API), this function will always return the
> running event loop.

**Comment by martindurant** [comment]
@pschork , are you interested in fixing this?
