### ISSUE TITLE
Cached files not expiring

### ISSUE THREAD

**Issue by arh89** [intake/filesystem_spec#413]
Hi all,

I just wanted to say fantastic software that you're building here – nice work!

I'm just getting started with `fsspec`, and I've been exploring the `WholeFileCacheFileSystem`, but I can't seem to get my cache to honour the `expiry_time`.

I've tried to come up with a minimal example which I think highlights the problem:

```python
import shutil
import fsspec
from fsspec.implementations.cached import WholeFileCacheFileSystem
import time

# create layered filesystem
fs = fsspec.filesystem('abfs',
                       account_name=BLOB_ACCOUNT_NAME,
                       credential=BLOB_CREDENTIAL)

fs = WholeFileCacheFileSystem(fs=fs,
                              cache_storage=CACHE_DIR,
                              cache_check=5,
                              check_files=False,
                              expiry_time=10,
                              same_names=True,
                              compression=None)

shutil.rmtree(CACHE_DIR, ignore_errors=True)

# get file
data = fs.open(PATH, mode='rb').read()
start_time = fs.cached_files[-1][PATH]['time']

# cache time..
print('Original cache time:', fs.last_cache - start_time)

# cache should have refreshed
time.sleep(5.01)
fs._check_cache()
print('Refreshed cache time:', fs.last_cache - start_time)

# file should still be valid... re-read
data = fs.open(PATH, mode='rb').read()
detail, _ = fs._check_file(PATH)
print('Cache file time:', detail['time'] - start_time)

# cache should have refreshed, now file should be invalid..
time.sleep(5.01)
fs._check_cache()
print('Refreshed cache time:', fs.last_cache - start_time)

# file should still be invalid... re-read
data = fs.open(PATH, mode='rb').read()
detail, _ = fs._check_file(PATH)
print('Cache file time:', detail['time'] - start_time)

elapsed_time = time.time() - start_time
print('Elapsed time', elapsed_time)
print(elapsed_time > fs.expiry)
```

Which produces the output:
```
Original cache time: 5.115365743637085
Refreshed cache time: 10.134422779083252
Cache file time: 0.0
Refreshed cache time: 15.154965877532959
Cache file time: 0.0
Elapsed time 15.159519910812378
True
```

Ultimately I think the there is a bug on [this line](https://github.com/intake/filesystem_spec/blob/9edbd645fd063d1445451be3089e2ffb5544467f/fsspec/implementations/cached.py#L206) with the comparison being the wrong way around (cache file time - current time will always be negative).

Hopefully I've not misunderstood what's happening here - happy to push up a PR if that helps.

**Comment by martindurant** [comment]
Thanks for the report!
I think the best thing to do, since I don't have azure to test against, would be to set this up a s a test function (in a PR) using one of the builtin filesystems like local, memory or ftp. I would not be too surprised if there is a sign error, and a test of expected behaviour would be the best way to capture it.
