### ISSUE TITLE
http implementation return error when URL contains "?"

### ISSUE THREAD

**Issue by gmaze** [intake/filesystem_spec#418]
When I try to fetch an URL with a "?" like this one:

```python
uri = "https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_center&time%3E=2026-12-20T00%3A00%3A00Z&time%3C=2026-12-27T14%3A48%3A20Z&distinct()"
```

which is a simple webAPI request, the ``http`` implementations throw an error because it can't "expand" this path:

```python
import fsspec
fs = fsspec.filesystem('http')
fs.get(uri, "toto.nc")
```
returns the error:
```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-48-ee357ddd0be1> in <module>
      5 uri = "https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_center&amp;time%3E=2026-12-20T00%3A00%3A00Z&amp;time%3C=2026-12-27T14%3A48%3A20Z&amp;distinct()"
      6 
----> 7 fs.get(uri, "toto.nc")

~/anaconda/envs/obidam36/lib/python3.6/site-packages/fsspec/asyn.py in get(self, rpath, lpath, recursive, **kwargs)
    240         rpath = self._strip_protocol(rpath)
    241         lpath = make_path_posix(lpath)
--> 242         rpaths = self.expand_path(rpath, recursive=recursive)
    243         lpaths = other_paths(rpaths, lpath)
    244         return sync(self.loop, self._get, rpaths, lpaths)

~/anaconda/envs/obidam36/lib/python3.6/site-packages/fsspec/spec.py in expand_path(self, path, recursive, maxdepth)
    722         """Turn one or more globs or directories into a list of all matching files"""
    723         if isinstance(path, str):
--> 724             out = self.expand_path([path], recursive, maxdepth)
    725         else:
    726             out = set()

~/anaconda/envs/obidam36/lib/python3.6/site-packages/fsspec/spec.py in expand_path(self, path, recursive, maxdepth)
    737                 out.add(p)
    738         if not out:
--> 739             raise FileNotFoundError(path)
    740         return list(sorted(out))
    741 

FileNotFoundError: ['https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_center&amp;time%3E=2026-12-20T00%3A00%3A00Z&amp;time%3C=2026-12-27T14%3A48%3A20Z&amp;distinct()']
```

going further, I found out that it is because ``glob.has_magic`` return True with the path string that the ``expand_path`` fails.
```python
glob.has_magic(uri)
>>> True
```

and finally, glob returns True because of the "?" in the URI:
```python
glob.has_magic(uri.replace("?",""))
>>> False
```

So, is this a bug in the internal fsspec machinery that should take more core with URLs in this case, or am I fetching this kind of webAPI the wrong way ?

Thanks for your help !
g

**Comment by martindurant** [comment]
Thanks, this is a good report.
I am not immediately sure what to do about it, since indeed "?" is both an expected character in http URLs, and also a special character when considering globing. Do you have an idea of something that might work for both? Perhaps for the special case of http, only "*" is considered for glob purposes.

**Comment by gmaze** [comment]
yes, may be for http url, only the "*" should be considered as magic, but not expert enough to be sure

in the mean time, I found a way around with cat_file that allows data to be fetched, but not as expected by fsspec design I guess:

```python
import fsspec
fs = fsspec.filesystem('http')

uri = "https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_center&time%3E=2026-12-20T00%3A00%3A00Z&time%3C=2026-12-27T14%3A48%3A20Z&distinct()"
# fs.get(uri, "toto.nc") # Not ok

data = fs.cat_file(uri) # Ok !
```

**Comment by martindurant** [comment]
Another workaround that I think might have worked:
```
fs.get([uri], "toto.nc")
```

**Comment by gmaze** [comment]
> `fs.get([uri], "toto.nc")`

unfortunately this does not work since it relies on the asyn.get() method (which fails in expand_path) as well

**Comment by martindurant** [comment]
What happens if you replace "?" with "%3F"?

**Comment by gmaze** [comment]
> What happens if you replace "?" with "%3F"?

Then it's the server which doesn't understand the request and returns 400 error

**Comment by martindurant** [comment]
OK, I should not be surprised by that.
Can you please look into how much work it would be to override the glob functionality in HTTPFileSystem, which would presumably involve a custom has_magic and glob re-replacement patterns. You would presumably need class attributes for the regex to use when checking for magics.... sounds a little painful.

By the way, using the _file non-expanding version is a perfectly fine solution.

**Comment by gmaze** [comment]
> Can you please look into how much work it would be to override the glob functionality in HTTPFileSystem

could you then assign me to this issue ? so that I don't forget about this ...

**Comment by martindurant** [comment]
I can also ping you periodically @gmaze !

**Comment by jmunroe** [comment]
Just stumbled upon the same issue.  For me, I came to it from trying to pull files from an ERDDAP serving and trying to use local caching.  I was initially puzzled as to why something like

```
import xarray as xr
import fsspec

uri = "https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_center&time%3E=2026-12-20T00%3A00%3A00Z&time%3C=2026-12-27T14%3A48%3A20Z&distinct()"

of = fsspec.open('simplecache::'+uri)
with of as f:
    ds = xr.open_dataset(f)
```

was throwing a `FileNotFoundError` but discovered that internally there was a `fs.get()` request that was trying to handle the ? as an expansion character as noted above.  However, using either

```
of = fsspec.open('filecache::'+uri)
with of as f:
    ds = xr.open_dataset(f)
```

or

```
of = fsspec.open('simplecache::'+uri, 
                 simplecache={"compression":'infer'})
with of as f:
    ds = xr.open_dataset(f)
```

seemed to trigger a different code path for downloading the file which bypasses the call to `fs.get()`. To get local copy of the file then some variation of 

```
of = fsspec.open('filecache::'+uri,
                 filecache={"cache_storage": "./",
                            "same_names": True})
with of as f:
    ds = xr.open_dataset(f)
```

could be used.  

Of course, making the change so that `fs.get()` does the right thing for HTTP is the right long term solution!

**Comment by martindurant** [comment]
Sorry I haven't had a chance to think about how to change glob specifically for HTTP yet.

**Comment by gmaze** [comment]
I keep thinking about it, but I really don't see how to handle this kind of request links.
May be the easiest way to proceed would be to identify the webAPI pattern <url>/<entry>?<parameters> and then to run the glob on the different components of the path, or just simply replace the `?` with another glob.has_magic safe character

**Comment by martindurant** [comment]
Sorry, I can't think of a way to solve this without copying a modified version of the whole of the glob method to http. That might be a reasonable thing to do, though. I'm still not sure what that logic would look like, though, except to say that "?" is special in this case,

**Comment by martindurant** [comment]
and so cannot be used for globbing at all.

**Comment by gmaze** [comment]
>  copying a modified version of the whole of the glob method to http

I don't think this would change a lot over time, so this would be the most appropriate solution
It's all in : https://github.com/python/cpython/blob/afe86066e748076f970ccd277fc64fc51bea189b/Lib/glob.py#L144
