### ISSUE TITLE
_run_until_done is incompatible with Python 3.6

### ISSUE THREAD

**Issue by cac04** [intake/filesystem_spec#425]
In commit 9f312ac3bbc9560ddeb9706e2754713af8ac01a2 the `_run_until_done` function was introduced.

This function calls `asyncio.current_task()` but that was only added to `asyncio` in Python 3.7 (see https://docs.python.org/3/library/asyncio-task.html#asyncio.current_task)

As a result, `fsspec` crashes if used with Python 3.6:

```
File "/usr/lib/python3.6/site-packages/fsspec/asyn.py", line 21, in _run_until_done
  task = asyncio.current_task()
AttributeError: module 'asyncio' has no attribute 'current_task'
```

Please could you change `setup.py` to reflect the new dependency on 3.7? e.g. something like this:

```
    python_requires=">3.7",
```

At the moment, `pip install fsspec` will install the latest version on a Python 3.6 system, which will then crash.

**Comment by martindurant** [comment]
Can I ask which backend you were using? As it stands, only http uses this, of the builtin backends in fsspec.
Updating the python_requires wouldn't help, because the old versions would still be there (and I think you have the inequality incorrect). But we *can* fix it probably, using `Task.current_task` . Would you like to try that?

**Comment by cac04** [comment]
> Updating the python_requires wouldn't help, because the old versions would still be there

Good point.

> I think you have the inequality incorrect

Also true!

> Can I ask which backend you were using?

I'm actually using `s3fs`, which has `fsspec` as a dependency.

> But we can fix it probably, using `Task.current_task`. Would you like to try that?

Sure - if compatibility with 3.6 can be maintained, that would be even better. I'm happy to help test that.

**Comment by martindurant** [comment]
> I'm actually using s3fs

OK, makes sense. 'll get back to you with the change.

**Comment by martindurant** [comment]
After a little trying, I **cannot** get this to work on py36. Please have a go, if you have any knowledge of this code!
In the meantime, we can explicitly say that async implementations don't work with py36 (but everything else does), and perhaps add an instantiation-time check into the async class, so that people installing in the future will know to downgrade fsspec or upgrade python.

**Comment by cac04** [comment]
I'm afraid I'm not familiar with this code. From the docs, it looks like you should be able to do `asyncio.Task.current_task()` until Python 3.7, and `asyncio.current_task()` from 3.7 onwards. I guess from your comment that it isn't that easy though!

An instantiation-time check sounds good though: at least then it would be clear what's going wrong, and that the solution is to downgrade fsspec or upgrade Python, without having spend time debugging.

**Comment by martindurant** [comment]
Yes, but there are other lines following that also don't work.

> An instantiation-time check sounds good though

Would you like to submit this?

**Comment by cac04** [comment]
I took a quick look at this code but it seems to require `tox` and `conda`, neither of which I have installed or used before. Conda looks like it's a whole new package management system, which isn't something I really want to install. Is there a simple way to run tests for this package without it?

**Comment by martindurant** [comment]
Certainly - just call `pytest` in the source directory. tox and conda are used for the CI, but you don't need to worry about it for local development, you can use `pip install -e .`, or whatever you normally do.

(as an aside, I generally do recommend conda, but that's a whole other conversation)

**Comment by cac04** [comment]
Thanks, I got that working. However, I see that in fact you've already added appropriate version checks in #426. So I guess this issue can be closed now.

**Comment by martindurant** [comment]
Of course, if you can solve it, that's even better! :)
Feel free to close, though.

**Comment by cac04** [comment]
If I ever have free time again, maybe I'll take a look at solving this properly :)
