### ISSUE TITLE
GCS filesystem breaks contract for uploading a file into directory

### ISSUE THREAD

**Issue by namanjain** [intake/filesystem_spec#448]
When uploading a file into a GCS directory, the [put API documentation](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.put) says that the file would go inside the directory. Any remote path with an ending slash "/" is considered as a dir.

When I tried it out, it didn't work as expected.

```
>>> import fsspec
>>> fs = fsspec.filesystem("gcs")
>>> with open("/tmp/myfile", "w") as f:
...   f.write("foo bar")
...
7
>>> fs.put("/tmp/myfile", "gs://naman-scratch/myfolder/")
>>> fs.isdir("gs://naman-scratch/myfolder")
False
>>> fs.isfile("gs://naman-scratch/myfolder")
True
```

As you can see, the directory name is stripped of the ending slash, and the file is uploaded with dir name (instead of inside it). 

From what I gather, this seems to be a bug in [AsyncFileSystem.put](https://github.com/intake/filesystem_spec/blob/6b32115fa98cfc46ec683a2b8df69ec0f04377f9/fsspec/asyn.py#L255) method, which calls [AbstractFileSystem._strip_protocol](https://github.com/intake/filesystem_spec/blob/6b32115fa98cfc46ec683a2b8df69ec0f04377f9/fsspec/spec.py#L162) method, which removes the ending slash. Most of the implementations probably don't have this problem because they override the `_strip_protocol` method, but gcsfs doesn't. But the bug seems to be in fsspec codebase.

**Comment by martindurant** [comment]
Does recursive=True (but still on a single file) do the right thing, or passing `["/tmp/myfile"]` instead of a string path alone?

I think there may be an argument for updating the doc rather than changing the behaviour.

**Comment by namanjain** [comment]
No, none of those work. They all create a file on GCS.

I tried the same thing with `LocalFileSystem` and that treats the `rpath` as a dir if it ends with ending slash. So if you change the documentation, "file" filesystem would have the wrong implementation. I'm sure there are other filesystems that follow the documentation too.

**Comment by namanjain** [comment]
@martindurant I have a fix for this as well. All we have to do is override `_strip_protocol` method in `gcsfs` with how other implementations have overridden them. The diff basically looks like:

```
+from fsspec.utils import infer_storage_options

+    @classmethod
+    def _strip_protocol(cls, path):
+        return infer_storage_options(path)["path"]
```

How do I open a PR in gcsfs? Should I fork the [dask/gcsfs](https://github.com/dask/gcsfs) repo?

**Comment by namanjain** [comment]
I opened a [PR](https://github.com/dask/gcsfs/pull/297) for this fix. Although for some reason, I can't add you to it.

**Comment by martindurant** [comment]
You don't need to add me, just to "allow edits by maintainers", but I wouldn't ordinarily do that except for PRs that have been orphaned. I won't look at this until next week now.
