### ISSUE TITLE
expand_path fails with recursive magic

### ISSUE THREAD

**Issue by ahirner** [intake/filesystem_spec#456]
```python
from fsspec.implementations.local import LocalFileSystem
fs = LocalFileSystem()
fs.expand_path("./*", recursive=True)
# TypeError: unsupported operand type(s) for +=: 'set' and 'list'
```
[This](https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L793) should probably be `out |= set(self.expand_path(p))`

**Comment by martindurant** [comment]
Thanks for the note.
Can you please write this as a test and include the fix in a PR?
