### ISSUE TITLE
Handling incorrect content-length headers

### ISSUE THREAD

**Issue by TomAugspurger** [intake/filesystem_spec#47]
From https://github.com/intake/intake/issues/367

```python

>>> x = len(dd.read_csv("https://raw.githubusercontent.com/hadley/nycflights13/master/data-raw/airports.csv").compute())
>>> y = pd.read_csv("https://raw.githubusercontent.com/hadley/nycflights13/master/data-raw/airports.csv")
>>> len(x), len(y)
(519, 1458)
```

@martindurant thinks this may be because Github's HTTP server isn't respecting the `'identity'` request header, and is sending back the compressed content length instead.

How should we handle this situation?

**Comment by martindurant** [comment]
This is now fixed
