### ISSUE TITLE
in 0.8.4 WholeFileCacheFileSystem._open() calls target with fs.get()

### ISSUE THREAD

**Issue by quai20** [intake/filesystem_spec#489]
Hi there, 

I noticed a change from 0.8.3 to 0.8.4, that breaks our use of **fsspec** in [argopy](https://github.com/euroargodev/argopy). 
From a `WholeFileCacheFileSystem` instance, the `_open()` function is now calling the target filesystem with `self.fs.get(path, fn)`.
On 0.8.3, it was directly the `_open()` from the target filesystem.

In our particular case, target filesystem is **http** and **path** is an url for an erddap server call. Path example :

`https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_mode,latitude,longitude,position_qc,time,time_qc,direction,platform_number,cycle_number,config_mission_number,vertical_sampling_scheme,pres,temp,psal,pres_qc,temp_qc,psal_qc,pres_adjusted,temp_adjusted,psal_adjusted,pres_adjusted_qc,temp_adjusted_qc,psal_adjusted_qc,pres_adjusted_error,temp_adjusted_error,psal_adjusted_error&longitude>=-70&longitude<=-65&latitude>=35.0&latitude<=40.0&pres>=0&pres<=10.0&time>=1325376000.0&time<=1330560000.0&distinct()&orderBy("time,pres")'`
 
The problem is that with `self.fs.get(path, fn)` (AsyncFileSystem), our path is going through `fs.expand_path()` and this latter raises an **FileNotFoundError** because `has_magic(path)` is true (erddap url has glob special characters) and `fs.glob(path)` returns an empty str. 

Is that the correct behaviour ? do I miss something ? 
If so, what's your advice to get our caching for erddap url working with 0.8.4 ?

Thanks,

Kevin

**Comment by martindurant** [comment]
Lets fix this as suggested in https://github.com/intake/filesystem_spec/issues/418 : make the glob-related functions special for HTTP and not include "?" as a magic character.
