### ISSUE TITLE
to_json failing when manually stacking multiple filesystem objects.

### ISSUE THREAD

**Issue by mraspaud** [intake/filesystem_spec#491]
When creating a zip filesystem of an s3 stored file, by creating the filesystem instance myself, the resulting filesystem crashes the `to_json` is called with: `Object of type S3File is not JSON serializable`.

However this works if I use the `.fs` of the open file instances I get when using `fsspec.open_files`.

Am I doing something wrong?

```python
    import fsspec
    from s3fs import S3FileSystem
    from fsspec.implementations.zip import ZipFileSystem

    filename = "sentinel-s3-ol2wfr-zips/2020/11/03/S3B_OL_2_WFR____20201103T100807_20201103T101107_20201103T121330_0179_045_179_1980_MAR_O_NR_002.zip"

    # This works fine
    json_fs = fsspec.open_files("zip://**/*.nc::s3://" + filename, s3={'anon': False, 'client_kwargs': {"endpoint_url":ENDPOINT}})[0].fs.to_json()
    print(json_fs) 
    # {"cls": "fsspec.implementations.zip.ZipFileSystem", "protocol": "zip", "args": [], "target_protocol": "s3", "target_options": {"anon": false, "client_kwargs": {"endpoint_url": "https://redacted.com"}}, "fo": "s3://sentinel-s3-ol2wfr-zips/2020/11/03/S3B_OL_2_WFR____20201103T100807_20201103T101107_20201103T121330_0179_045_179_1980_MAR_O_NR_002.zip"}

    s3 = S3FileSystem(anon=False, client_kwargs={"endpoint_url":ENDPOINT})
    s3file = s3.open(filename)
    zip = ZipFileSystem(s3file)
    # this crashes
    zip.to_json()
    # Object of type S3File is not JSON serializable
```

**Comment by martindurant** [comment]
The issue seems to be that filesystems are json-serialisable, but files not. In the first case, it is a file path that gets passed, not an object. The equivalent would be:
```
opts = dict(anon=False, client_kwargs={"endpoint_url":ENDPOINT})
zip = ZipFileSystem(filename, target_protocol="s3", target_options=opt)
```
(although internally, ZipFileSystem actually uses `open_files` rather than directly instantiating the file system). 

I don't know how one would make JSON automatically be able to serialise the file nested in a filesystem, except to override its `to_json` method to return the path string instead.

**Comment by mraspaud** [comment]
Thanks for the explanation, I understand now that what I originally though was nested filesystem (using "zip://...::s3://...") is actually 'only' specifying the protocol for the zip file to use.
Even though I think it would be nice feature to have, I'm closing this issue as it's not the bug I thought it was.

**Comment by martindurant** [comment]
Your point was still valid, and I would welcome someone fixing it - but I don't think its at the top of anyone's priorities.
