### ISSUE TITLE
feature request: dbfs

### ISSUE THREAD

**Issue by raybellwaves** [intake/filesystem_spec#495]
dbfs as in Databricks File System (https://docs.databricks.com/data/databricks-file-system.html)

I can write the pyspark.sql.dataframe.Dataframe to a parquet file and use data.dataframe.read_parquet to read it in. However, I tend to use tables (dbfs) for efficient usage on databricks. I also use delta tables which are essentially a way of adding version numbers to tables (https://docs.delta.io/latest/index.html).

It would be nice to bring this data into the pydata ecosystem for creating dashboards, EDA, machine learning etc.

I started taking a look at this over at dask-sql using pyhive https://github.com/nils-braun/dask-sql/issues/83

**Comment by martindurant** [comment]
Looks very doable given the API at https://docs.databricks.com/dev-tools/api/latest/dbfs.html 

However, the docs seems to suggest that intended usage is to *mount* the FS, so you can interact with it as local files. Is this method lacking? Are you looking for something that you can access from outside the cluster?

**Comment by raybellwaves** [comment]
Thanks. Wasn't familiar with that API. I'll check it out.

Yes. Ideally outside of the cluster. e.g. (for dask sql) instead of
`c.create_table("taxi", "az://nyctlc/green/puYear=2019/puMonth=1/*.parquet", storage_options=storage_options)`
it could be
`c.create_table("taxi", "dbfs://nyctlc.green", storage_options=storage_options)`

**Comment by martindurant** [comment]
Setting it up looks pretty simple, but I have no idea how you would go about testing it

**Comment by raybellwaves** [comment]
Likewise. Would be nice to get help from databricks folks. Or if there is something like azurite which is used for testing adlfs.

**Comment by martindurant** [comment]
> if there is something like azurite

I'm not aware of it, but someone should at least search around.

**Comment by nils-braun** [comment]
I have unfortunately also not found any test/mock software (in general it seems, the ecosystem for client software to be used outside of the cluster is quite rare for dbfs). I think one would need to mock the API ourselves...
However, as we only need the `dbfs` part, it is only around 10 endpoints. I am happy to help here if you like!

**Comment by martindurant** [comment]
I suppose we could always record with vcrpy, so long as *some* developer has access to a real cluster; but my experience with gcsfs suggests this is often more pain than it's worth.

> However, as we only need the dbfs part, it is only around 10 endpoints. I am happy to help here if you like!

That would be great! Perhaps we could make our own mini "brickulite".

**Comment by nils-braun** [comment]
I have just seen that the databricks CLI tool has some tests, maybe we could learn from them: https://www.github.com/databricks/databricks-cli/tree/master/tests

Maybe we could also just use their API python implementation and code against this. We would then only need to mock this part, which should be mich easier (as they will fix their CLI tool probably much faster than we do)

**Comment by martindurant** [comment]
https://github.com/databricks/databricks-cli/blob/master/tests/dbfs/test_api.py#L81 ?

**Comment by nils-braun** [comment]
Yes. Sorry, I did not have the time to look into it in more detail. It is not a lot and it seems they are just mocking away their own API implementation. 
Might still be worth to maybe use their code, so that we do not need to implement the server interaction again. 
I would be able to have a look into it next weekend, but if anyone has already some time before that, I am happy to contribute.
