### ISSUE TITLE
HTTP backend has flaky behavior when enumerating the directory index

### ISSUE THREAD

**Issue by amotl** [intake/filesystem_spec#506]
Dear @martindurant, @TomAugspurger and contributors,

first things first: Thanks a stack for conceiving and maintaining this excellent library.

@gutzbenj is currently migrating the data acquisition backend of [wetterdienst](https://github.com/earthobservations/wetterdienst) to use `fsspec` for downloading data from the HTTP server at https://opendata.dwd.de/. For ingesting the directory index, we are currently using a hand-rolled implementation [1] based on BeautifulSoup and lxml.

Now that we are switching to fsspec, we found that it would **randomly** include a **single folder** within its results list when enumerating a remote HTTP filesystem using `fs.find(url)`. It is expected that it would only return **files** as results, right? We added a concise repro at [2].

The respective folder is not always the same, so the behavior is flaky. It can be revealed by invoking the examples [1] vs. [2] by using:
```
# Run current implementation.
python list-remote-files-dwd.py | grep -v zip

# Run implementation based on fsspec.
python fsspec-dwd.py | grep -v zip
```

Alternatively, this produces a deterministic yet wrong result when counting the number of enumerated files:
```
python list-remote-files-dwd.py | wc -l
  194595
python fsspec-dwd.py | wc -l
  194596
```
The result list count of the fsspec-based implementation is off by one.

Thank you in advance for taking the time to look into this.

Keep up the spirit and with kind regards,
Andreas.

[1] https://gist.github.com/gutzbenj/88e69d10447698d099f7227a731add9b
[2] https://gist.github.com/amotl/9fc67b696cbab9f0667be60de4dcf2be

P.S.: We are using Python 3.8 and fsspec 0.8.5.

**Comment by amotl** [comment]
We thought it would only happen on large trees, but actually it doesn't. So we amended the repro programs to run on arbitrary URLs and wanted to take the chance to provide an alternative DWD_URL because the runtime on it is much lower.

### Setup
```
wget https://gist.githubusercontent.com/gutzbenj/88e69d10447698d099f7227a731add9b/raw/list-remote-files-dwd.py
wget https://gist.githubusercontent.com/amotl/9fc67b696cbab9f0667be60de4dcf2be/raw/fsspec-dwd.py
```

### Configure
```
export DWD_URL=https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily
```

### Invoke
And then run the examples like:
```
# Run current implementation.
python list-remote-files-dwd.py | egrep -v "(txt|pdf|zip)"

# Run implementation based on fsspec.
python fsspec-dwd.py | egrep -v "(txt|pdf|zip)"
```

**Comment by martindurant** [comment]
Do I understand correctly that you get one extra entry, but which entry you get is random? Is it at least a real entry, or something completely unexpected?

You are right that `find()` is supposed to return only files, by default.

I don't think that find/walk is well tested for HTTP, because there is no real "directory" - actually there is always a "file", but you can infer a dictionary if it contains further links. In practice, we look for a "/" suffix to guess directory, as indeed does your script
```
        if not f.endswith("/"):
            files.append(urljoin(url, f))
        else:
            folders.append(urljoin(url, f))
```
versus
```
         "type": "directory" if u.endswith("/") else "file",
```

fsspec is not being non-deterministic is strange, though. I would have thought the listings came back in the same oder every time, so this would suggest perhaps extra calls are happening. You can configure logger "fsspec.http" to find out the calls being made. Any improvement to the robustness of ls/walk in http would be greatly appreciated!

**Comment by amotl** [comment]
Hi Martin,

thanks for taking the time to answer on our observations.

> fsspec is not being non-deterministic is strange, though.

We also first thought that the server might be responding indeterministically. That's why we decided to accompany the fsspec-based test case with a short test case based on our current routine.

> Any improvement to the robustness of ls/walk in http would be greatly appreciated!

I believe @gutzbenj already dedicated some time to this yesterday and he quickly mentioned that the flaw was even in the core module `spec.py` around [1]. Maybe it only manifests within the scope of the interaction with the HTTP backend? I did not go into the details and I am happy that Benjamin was able to investigate further. In this manner, I don't want to spread any rumors - let's wait for him to come back providing a patch, preferably accompanied by a respective test case.

With kind regards,
Andreas.

[1] https://github.com/intake/filesystem_spec/blob/a5bb95155b450ec2443872a45a4a58ce90748297/fsspec/spec.py#L434-L437

**Comment by martindurant** [comment]
> let's wait for him to come back providing a patch

Certainly.

I will comment that, as I mentioned, there is not a concrete way to say if a URL is meant to be a directory or a file. Currently, `isfile` says True for any URL that is reachable (which means calling this server, every time), but in this context is might be reasonable to replace with
```
    async def _isfile(self, path, **kwargs):
        return path.endswith("/")
```

**Comment by amotl** [comment]
> I will comment that, as I mentioned, there is not a concrete way to say if a URL is meant to be a directory or a file.

Yeah. Sad but true.

> in this context is might be reasonable to replace [...]

That sounds reasonable, thanks a bunch for adding your insights and even a specific suggestion. I hope Benjamin will get a chance to validate this and eventually submit a patch.

**Comment by gutzbenj** [comment]
Dear Martin,

I have handed in a small patch with #507 . What we've seen is resulting from a variable naming in the ``find()`` method. I simply added an underscore to the **path** variable (-> **path_**) coming from self.walk() to supress this behaviour.
