### ISSUE TITLE
faster .exists() ?

### ISSUE THREAD

**Issue by majidaldo** [intake/filesystem_spec#509]
I'm using the Azure blobstore backend, `'az'`/`adlfs`. I do many `.exists` checks in my code. But the abstract implementation, using `fs.info` , is pretty slow.

After fixing #468 , checking existence through `ls` is much faster.
```
try:
    fs.ls(location)
    return True
 except FileNotFoundError:
     return False
```

Just putting this here as a possible improvement. Maybe it goes in the `adlfs` repo. idk.

**Comment by martindurant** [comment]
Why is `fs.info` so much slower than `fs.ls` ?

**Comment by TomAugspurger** [comment]
I'm guessing `info` vs. `ls` is a red herring. The newest version of adlfs sped up `.exists()` my using a dedicated method from `azure.stroage.blob` (the old way was based around listing files). I don't think there's anything for fsspec to do.

**Comment by majidaldo** [comment]
Doesn't `fs.info` extract more info than needed for file existence?

**Comment by martindurant** [comment]
No, it's a single call either way.

**Comment by martindurant** [comment]
Closing as probably fixed. Please raise with adlfs if this is still a problem.

**Comment by majidaldo** [comment]
It's still a problem: `ls` comes back in us while `exists` comes back in ms. But I agree it's something with adlfs
