### ISSUE TITLE
fs.exists issue with s3fs

### ISSUE THREAD

**Issue by oeway** [intake/filesystem_spec#518]
I notice a wired behavior with fs.exists with s3 backend. After calling `fs.exists` on a folder (perhaps I should not), checking `fs.exists` on a file inside it returns False.

See the experiment below:
```python
>>> import fsspec
>>> fs = fsspec.filesystem('s3', key='my_key', secret='my_secret', client_kwargs={
...     "endpoint_url": 'https://mys3-server.com'
...     "region_name": 'EU'
... })

>>> fs.touch('/my-bucket/my_folder/my_file.json')
>>> fs.exists('/my-bucket/my_folder/my_file.json')
True
>>> fs.exists('/my-bucket/my_folder/')
True
>>> fs.exists('/my-bucket/s/my_folder/my_file.json')  # <------------This should be True
False
>>> fs.invalidate_cache('/my-bucket/my_folder/my_file.json')
>>> fs.exists('/my-bucket/my_folder/my_file.json')
True
>>> fs.exists('/my-bucket/my_folder/')
True
>>> fs.exists('/my-bucket/my_folder/my_file.json')  # <------------This should be True
False
```

**Comment by ajkerrigan** [comment]
Hi @oeway - I can't seem to reproduce that behavior with my own S3 buckets. A few questions:

- Which versions of `s3fs` and `fsspec` are you using?
- Are you using AWS S3 or another product with an S3-compatible API? If it's not AWS S3, which product is it?

As a side note, for S3 cases I typically see folks use `s3fs` so the `fsspec` bits are all below the surface. I don't think that's the problem here, just curious about the motivation for using fsspec directly.

**Comment by oeway** [comment]
HI @ajkerrigan  Thanks for looking into this.
```python
>>> import s3fs
>>> s3fs.__version__
'0.4.2'
>>> import fsspec
>>> fsspec.__version__
'0.7.4'
```

The S3 server is a. minio server started via their docker image (`minio/minio:RELEASE.2020-07-02T00-15-09Z`).

> As a side note, for S3 cases I typically see folks use s3fs so the fsspec bits are all below the surface. I don't think that's the problem here, just curious about the motivation for using fsspec directly.

I would like to switch backend implementation for different cases, so having a more consistent way of initialising the file system seems more straightforward for my case.

**Comment by oeway** [comment]
Well, after upgrading it to the latest version, I the issue disappeared:
```
>>> import fsspec
>>> fsspec.__version__
'0.8.5'
>>> import s3fs
>>> s3fs.__version__
'0.5.2'
>>> import boto3
>>> boto3.__version__
'1.14.9'
```

However, in my other application, I still the fs.exists still return False for existing files with the latest version above. I had to insert `fs.invalid_cache()` when I use `fs.exists`.

It will take more time to get a minimal reproducible version for this issue, and I don't have bandwidth for the moment. In the meantime, maybe you can pin the version to `fsspec==0.7.4, s3fs==0.4.2` and see what's happening?

**Comment by ajkerrigan** [comment]
Thanks for the info - I'm glad updating addressed at least part of the issue.

For what it's worth this appears related to dask/s3fs#253. [This comment](https://github.com/dask/s3fs/issues/253#issuecomment-714627185) mentions exactly the issue you're seeing here, and I do reliably see that behavior with older s3fs/fsspec pinned. I'd expect updating to do the trick, but you may find other useful advice regarding caching in that thread.
