### ISSUE TITLE
Opening a remote HDF4 file with HTTPS

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/filesystem_spec#532]
I'm having trouble understanding the behavior opening up an HDF4 file via HTTPS:
https://hls.gsfc.nasa.gov/data/v1.4/S30/2017/13/T/E/F/HLS.S30.T13TEF.2017359.v1.4.hdf

If I download it locally (e.g. using fsspec simplecache), I can open it with rioxarray and get an xarray.Dataset object

If I try to open it remotely with fsspec using an https filesystem, it complains about subgroups. 

If I open it remotely using rioxarray without fsspec, it returns a xarray.DataArray object!

Here's [the reproducible notebook](https://nbviewer.jupyter.org/gist/rsignell-usgs/b631a685ccc7f30fa1488bb644aa9126).

**Comment by martindurant** [comment]
So... I think that rasterio knows how to open an HTTP URL directly somehow with some custom code built into the C layer, and returns a dataset. 
Passed an open file, it makes a reader context to load the whole thing into memory, and I suppose xarray doesn't know about the difference.

If I use `rasterio.open` directly, and enter the context manually, I get this:
```
rasterio/_base.pyx in rasterio._base.DatasetBase.__init__()

RasterioIOError: '/vsimem/20545c86-175c-4887-8589-767bb8d8d004/20545c86-175c-4887-8589-767bb8d8d004.tif' not recognized as a supported file format.
```

Both the xarray and rasterio behaviours happen even for an `io.BytesIO` object of the same data, so I don't suppose it's an fsspec issue.

So, I would report two issues:
- xarray doesn't account for rasterio returning a context for the case of file-like objects
- rasterio doesn't correctly open a file-like version of data which opens fine as an on-disk file (I would choose the smallest file you can find to show this)

**Comment by rsignell-usgs** [comment]
@martindurant thanks so much -- I will report these!

**Comment by sharkinsspatial** [comment]
@rsignell-usgs Can you provide a link to the related issues you reported here?  I was just throwing together some notebooks and ran into the same behavior.
