### ISSUE TITLE
glob can be slow on deeply nested structures

### ISSUE THREAD

**Issue by hhuuggoo** [intake/filesystem_spec#540]
I've noticed that s3fs (really fsspec) can be quite slow on deeply nested directory structures.  This is particularly relevant when I'm reading data written to S3 by some devops tool, which nests year/month/date/hours/minutes etc.

I was wondering if any thought had been given to speeding this up by parallelizing the recursive calls to walk? 

https://github.com/intake/filesystem_spec/blob/c2b6eabd37bf8c10222f17e8a816e19b43c70c01/fsspec/spec.py#L412

I was going to try doing this in a thread pool executor - I realize this may be an issue since I don't believe boto3 is thread-safe.

Thanks!

**Comment by martindurant** [comment]
You would probably want to make use of the existing async functionality rather than trying to use threads (since then you would have a nasty mix of threads and ioloops). You would also need to make assumptions around how the set of unknown paths might be structured, which is a hard thing to do.

Actually `find(maxdepth=None)` should saturate the bandwidth, I would think - it gets all nested objects in a single call. Is the codepath really hitting recursion?

**Comment by hhuuggoo** [comment]
> You would probably want to make use of the existing async functionality rather than trying to use threads (since then you would have a nasty mix of threads and ioloops). You would also need to make assumptions around how the set of unknown paths might be structured, which is a hard thing to do.
> 
> Actually `find(maxdepth=None)` should saturate the bandwidth, I would think - it gets all nested objects in a single call. Is the codepath really hitting recursion?

Not sure - I thought I knew what was going on just by looking at the code but I'll validate what I think is happening and report back.  Thanks!

**Comment by martindurant** [comment]
Actually, my comment about find only applies to some implementations. Which are you using?

On February 15, 2021 11:54:20 PM EST, hhuuggoo <notifications@github.com> wrote:
>> You would probably want to make use of the existing async
>functionality rather than trying to use threads (since then you would
>have a nasty mix of threads and ioloops). You would also need to make
>assumptions around how the set of unknown paths might be structured,
>which is a hard thing to do.
>> 
>> Actually `find(maxdepth=None)` should saturate the bandwidth, I would
>think - it gets all nested objects in a single call. Is the codepath
>really hitting recursion?
>
>Not sure - I thought I knew what was going on just by looking at the
>code but I'll validate what I think is happening and report back. 
>Thanks!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/filesystem_spec/issues/540#issuecomment-779580326

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martindurant** [comment]
Right, sorry - s3fs - then find should be one-shot

On February 15, 2021 4:22:56 PM EST, hhuuggoo <notifications@github.com> wrote:
>I've noticed that s3fs (really fsspec) can be quite slow on deeply
>nested directory structures.  This is particularly relevant when I'm
>reading data written to S3 by some devops tool, which nests
>year/month/date/hours/minutes etc.
>
>I was wondering if any thought had been given to speeding this up by
>parallelizing the recursive calls to walk? 
>
>https://github.com/intake/filesystem_spec/blob/c2b6eabd37bf8c10222f17e8a816e19b43c70c01/fsspec/spec.py#L412
>
>I was going to try doing this in a thread pool executor - I realize
>this may be an issue since I don't believe boto3 is thread-safe.
>
>Thanks!
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/filesystem_spec/issues/540

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
