### ISSUE TITLE
release > 0.8.5?

### ISSUE THREAD

**Issue by raybellwaves** [intake/filesystem_spec#543]
Any interest in releasing a version > 0.8.5 to expose the newly added `dbfs` protocol? https://github.com/nils-braun/dask-sql/pull/140

**Comment by martindurant** [comment]
Yes, will do. 

Note that the pypi badge on the README still doesn't seem to show right.

**Comment by martindurant** [comment]
https://pypi.org/project/fsspec/

**Comment by martindurant** [comment]
Note to self to go back and update release history notes...
