### ISSUE TITLE
LocalFileSystem: OSError: [Errno 18] Invalid cross-device link

### ISSUE THREAD

**Issue by espdev** [intake/filesystem_spec#544]
Hello,

I get the following error when I try to use `LocalFileSystem` on WSL and write a file to Windows directory (the directory on host):

```
Traceback (most recent call last):
  File "... /fsspec/transaction.py", line 24, in __exit__
    self.complete(commit=exc_type is None)
  File "... /fsspec/transaction.py", line 37, in complete
    f.commit()
  File "... /fsspec/implementations/local.py", line 246, in commit
    os.replace(self.temp, self.path)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpursl97uu' -> '/mnt/c/Temp/file_name'
``` 

I think that when we use `os.replace` we will get cross-device link errors whenever the devices of the source and the destination paths are not same. Most likely I will get the same error when I will try to write to path on any mounted FS from another device. I found a similar issue: https://github.com/intake/filesystem_spec/issues/322

**Comment by martindurant** [comment]
Yes you appear to be right, and we are assuming that the temporary store and the target for the file are on the same device. I'm not sure how to best fix this - any thoughts?

**Comment by espdev** [comment]
@martindurant 
>  I'm not sure how to best fix this - any thoughts?

I have encountered a similar issue in my code when I was doing atomic write to mounted GlusterFS with a similar way through a temp file. I just used `shutil.move` instead of `Path.rename` function and it worked in my case. I guess it might not be very efficient in general.

**Comment by martindurant** [comment]
It could be a try/except where the backup path uses `move`, as you suggest. Would you like to contribute this change? I don't suppose we have a way to trigger it in CI tests.

**Comment by espdev** [comment]
I think we just can use `shutil.move`. The [documentation](https://docs.python.org/3/library/shutil.html#shutil.move) says:

> If the destination is on the current filesystem, then os.rename() is used. Otherwise, src is copied to dst using copy_function and then removed. In case of symlinks, a new symlink pointing to the target of src will be created in or as dst and src will be removed.

I will try to make a pull request soon.

**Comment by martindurant** [comment]
OK, sounds good.
