### ISSUE TITLE
fsspec 0.8.6 fails if pyarrow is not installed

### ISSUE THREAD

**Issue by clowtown** [intake/filesystem_spec#545]
I believe this is caused by #503 

python 3.6 which worked on 0.8.5, now fails on 0.8.6.
`
File ".tox/plf/lib/python3.6/site-packages/fsspec/spec.py", line 81, in <module>
    pa_version = get_package_version_without_import("pyarrow")
  File ".tox/plf/lib/python3.6/site-packages/fsspec/utils.py", line 428, in get_package_version_without_import
    return importlib_metadata.distribution(name).version
  File ".tox/plf/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File ".tox/plf/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for pyarrow
`

Frozen requirements from failing run

`behave==1.2.6
boto3==1.9.203
boto3-type-annotations==0.3.1
botocore==1.12.232
certifi==2020.12.5
chardet==3.0.4
Cython==0.29.22
dataclasses==0.7
Deprecated==1.2.11
docutils==0.15.2
fastparquet==0.4.1
fsspec==0.8.6
idna==2.8
importlib-metadata==1.7.0
importlib-resources==3.3.0
jmespath==0.10.0
JSON-minify==0.3.0
llvmlite==0.35.0
marshmallow==3.8.0
marshmallow-dataclass==8.0.0
marshmallow-enum==1.5.1
mypy-extensions==0.4.3
ndjson==0.3.1
numba==0.52.0
numpy==1.16.6
packaging==20.9
pandas==0.24.2
parse==1.19.0
parse-type==0.5.2
pyparsing==2.4.7
python-dateutil==2.8.1
python-snappy==0.5.4
pytz==2021.1
requests==2.22.0
requests-aws-sign==0.1.6
s3fs==0.4.2
s3transfer==0.2.1
six==1.15.0
tenacity==6.2.0
thrift==0.13.0
typeguard==2.10.0
typing-extensions==3.7.4.3
typing-inspect==0.6.0
urllib3==1.25.11
wrapt==1.12.1
zipp==3.4.0
`

**Comment by martindurant** [comment]
Fixing, will re-release. It seems that on some versions, you get an ImportError, which is what I would have expected.
