### ISSUE TITLE
Enable documentation autobuild/preview  for PRs on Readthedocs

### ISSUE THREAD

**Issue by andersy005** [intake/filesystem_spec#549]
Now that Readthedocs provides automatic build of documentation for **pull requests**: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html, it would nice to enable this feature for this repo.

@martindurant, can you enable the above feature on [readthedocs](https://readthedocs.org/dashboard/filesystem-spec/advanced/) when you get a moment?

**Comment by martindurant** [comment]
Done
