### ISSUE TITLE
get_mapper() doesn't work on cached filesystems

### ISSUE THREAD

**Issue by alimanfoo** [intake/filesystem_spec#552]
If I used the top-level ``fsspec.get_mapper()`` function then I can use cached filesystems no problem, e.g.:

```python
>>> import fsspec
>>> m = fsspec.get_mapper("simplecache::gs://foo/bar")
>>> m.fs
<fsspec.implementations.cached.SimpleCacheFileSystem object at 0x7f09e55e1b10>
```

However, if I first instantiate a cached filesystem somehow, then call the ``get_mapper()`` method on the filesystem instance, the mapper ends up accessing the inner filesystem, e.g.:

```python
>>> fs, path = fsspec.core.url_to_fs("simplecache::gs://foo/bar")
>>> fs
<fsspec.implementations.cached.SimpleCacheFileSystem object at 0x7f09e55e1b10>
>>> m = fs.get_mapper(path)
>>> m.fs
<gcsfs.core.GCSFileSystem object at 0x7f09e550d610>
```

I suspect it is because the ``get_mapper()`` method on the cached filesystem class is getting passed through to the inner (target) filesystem, but shouldn't.

**Comment by martindurant** [comment]
Quite right, get_mapper should be one of the known methods dealt with in getattribute. I have not yet found an automated way to do this. You could have achieved it by calling AbstractFileSystem.get_mapper(fs).

On March 2, 2021 6:48:30 PM EST, Alistair Miles <notifications@github.com> wrote:
>If I used the top-level ``fsspec.get_mapper()`` function then I can use
>cached filesystems no problem, e.g.:
>
>```python
>>>> import fsspec
>>>> m = fsspec.get_mapper("simplecache::gs://foo/bar")
>>>> m.fs
><fsspec.implementations.cached.SimpleCacheFileSystem object at
>0x7f09e55e1b10>
>```
>
>However, if I first instantiate a cached filesystem somehow, then call
>the ``get_mapper()`` method on the filesystem instance, the mapper ends
>up accessing the inner filesystem, e.g.:
>
>```python
>>>> fs, path = fsspec.core.url_to_fs("simplecache::gs://foo/bar")
>>>> fs
><fsspec.implementations.cached.SimpleCacheFileSystem object at
>0x7f09e55e1b10>
>>>> m = fs.get_mapper(path)
>>>> m.fs
><gcsfs.core.GCSFileSystem object at 0x7f09e550d610>
>```
>
>I suspect it is because the ``get_mapper()`` method on the cached
>filesystem class is getting passed through to the inner (target)
>filesystem, but shouldn't.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/filesystem_spec/issues/552

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alimanfoo** [comment]
Thanks @martindurant :pray:
