### ISSUE TITLE
Different CachingFileSystem instances compare equal

### ISSUE THREAD

**Issue by gerritholl** [intake/filesystem_spec#577]
Different `CachingFileSystem` instances compare equal, even if they have different properties:

```
from fsspec.implementations.cached import CachingFileSystem
from fsspec.implementations.local import LocalFileSystem
lfs = LocalFileSystem()
cfs = CachingFileSystem(
        fs=LocalFileSystem(),
        cache_storage="/data/gholl/cache/dummy",
        cache_check=600,
        check_files=False,
        expiry_times=False,
        same_names=False)
cfs2 = CachingFileSystem(
        fs=LocalFileSystem(),
        cache_storage="/data/gholl/cache/dummy2",
        cache_check=900,
        check_files=False,
        expiry_times=True,
        same_names=True)
print(cfs == cfs2)
```

Running this gives `True`.  I would expect it to give `False`, because those `CachingFileSystem`s are clearly not equal.

**Comment by martindurant** [comment]
It seems that `cfs._fs_token` is picking up `lfs`'s token. Caching file systems have a [custom getattribute](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/cached.py#L356) for looking up methods/attributed in the cacher as opposed to the target, that's where this will be fixed. 

Would you like to work on this?

**Comment by gerritholl** [comment]
Possibly related to this and #576:

```
In [15]: CachingFileSystem(fs=LocalFileSystem()).to_json()
Out[15]: '{"cls": "fsspec.implementations.local.LocalFileSystem", "protocol": "file", "args": []}'
```

I will have a look if I can figure out how this should be fixed.
