### ISSUE TITLE
Glob search breaks when '?' occurs before '*'

### ISSUE THREAD

**Issue by maciejb** [intake/filesystem_spec#58]
I originally filed this under s3fs ([here](https://github.com/dask/s3fs/issues/189)), but adding it here as related:

Consider for example:
`fs.glob('mybucket/*/????/*.zip')`
returns
`['mybucket/folder/2018/file.zip', 'mybucket/folder/2019/file.zip']`
whereas
`fs.glob('mybucket/folder/????/*.zip')`
returns
`[]`

If the * is after the ?, the ? ends up in the path that gets walked, and so it doesn't find the path. Instead of searching the * only, this bit should consider other characters:
https://github.com/intake/filesystem_spec/blob/c0c4f2bfa69127f5d6daf81b98b8584669041468/fsspec/spec.py#L417

**Comment by martindurant** [comment]
@maciejb , would you like to have a crack at this? `fnmatch.translate` gives a fuller regex considering `*`, `?` and `[..]`, but the root problem of finding the top level of absolute path remains the same.

**Comment by maciejb** [comment]
Sure, I'll give it a shot this week

**Comment by maciejb** [comment]
....or did you just beat me to it? :) #61

**Comment by martindurant** [comment]
Yes, sorry - I wanted to get fsspec ready for release
