### ISSUE TITLE
`LocalFileSystem.isdir` inconsistent with `os.path.isdir` with symbolic links

### ISSUE THREAD

**Issue by ethanwharris** [intake/filesystem_spec#591]
We had a bit of a subtle bug here: https://github.com/PyTorchLightning/pytorch-lightning/pull/6730

Because `LocalFileSystem.info` returns `t: 'link'` for sym linked files / directories, `isdir` will always be false. This is inconsistent with the behaviour of `os.path.isdir` which follows sym links. We've been able to fix this by overriding `isdir` to just return `os.path.isdir`. I guess that this behaviour isn't intended? Not sure what the best fix is, overriding `isdir` works but is not the prettiest solution :smiley:

**Comment by martindurant** [comment]
I think it would be fair to follow whatever `os` does. It will mean breaking the weak requirement that `info["type"]` be "directory", but I'm not too worried about that.
