### ISSUE TITLE
`infer_compression` doesn't work with CAPITAL file extensions.

### ISSUE THREAD

**Issue by itsbenweeks** [intake/filesystem_spec#594]
E.g. `fs.open('test.ZIP')` will not choose the `zip` interpreter. While choosing to `fs.open('test.ZIP', compression='zip')` would work, I'm dealing with an external call for fsspec that does not pass kwargs. I'd prefer to `.lower()` the string at https://github.com/intake/filesystem_spec/blob/master/fsspec/utils.py#L120 to address this.

**Comment by martindurant** [comment]
Certainly, sounds reasonable a fix. Will you be submitting a PR?

**Comment by itsbenweeks** [comment]
I will :)
