### ISSUE TITLE
ImportError: cannot import name 'maybe_sync'

### ISSUE THREAD

**Issue by CarlosSchmidt01** [intake/filesystem_spec#597]
Hey guys,

I have a python script using s3fs and I got an error when import this package.
s3fs use fsspec and after a release 0.9.0 an error start to appear

```
Traceback (most recent call last):
  File "/tmp/my_script.py", line 4, in <module>
    import s3fs
  File "/usr/local/lib/python3.6/site-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/usr/local/lib/python3.6/site-packages/s3fs/core.py", line 12, in <module>
    from fsspec.asyn import AsyncFileSystem, sync, sync_wrapper, maybe_sync
ImportError: cannot import name 'maybe_sync'
```

To solve this issue I install an old version from fsspec

**Comment by martindurant** [comment]
Please bear with me: fsspec was released today, but s3fs not yet. It should be ready within a day or so.

**Comment by CarlosSchmidt01** [comment]
No problem, it just for your knowledge and for help any person who have the same issue

**Comment by martindurant** [comment]
v0.6.0 on pypi

**Comment by martindurant** [comment]
0.6.0 on pypi

**Comment by dave-kennedy** [comment]
Can this incompatibility be flagged somehow? Maybe add a test in requirements or setup script, like if s3fs is installed and s3fs version is less than [whatever] throw an error?

**Comment by martindurant** [comment]
s3fs versions from now on have exact pinning on fsspec, so this won't happen in the future.

**Comment by dave-kennedy** [comment]
@martindurant thanks for the reply. What I mean is I have a project that depends on s3fs==0.5.2, which depends on fsspec>=0.8.0, which pulls in fsspec 2021.04.0, which is incompatible with 0.5.2 but happily installs anyways. Does that make sense?

**Comment by martindurant** [comment]
Understood, but I don't think there's anything we can do about it now, except to ask you to specify your versions exactly. Sorry. 
Why do you need the older s3fs?

**Comment by dave-kennedy** [comment]
@martindurant I may not need that version specifically. It was in the requirements for a project I inherited and was surprised at the behavior. So there's no way to tell pip not to install fsspec==2014.04.0 if s3fs==0.5.2 is installed?

**Comment by martindurant** [comment]
Yes, of course - add fsspec with the right version to the requirements. 
There is no way to tell pip in the case that the requirements includes s3fs==0.5.2 only.

**Comment by arogozhnikov** [comment]
for anyone running into the same issue these days - for me it was resolved by manually updating both s3fs and fsspec to >= 2021.10

**Comment by suryalilly** [comment]
@arogozhnikov I have tried updating the s3fs and fspec to >= 2121.10 even though i am getting the error:  "cannot import name 'maybe_sync' from 'fsspec.asyn' (/opt/python/fsspec/asyn.py)", do you have any idea on this?

**Comment by martindurant** [comment]
You seem to have your python in a system directory, which is not good practice. I recommend using an environment manager like conda of venv to make sure you don't mess with system libraries.

Please check the locations of your fsspec and s3fs libraries, and the `__version__` reported for them within python.
