### ISSUE TITLE
fsspec 0.9.0 causes gcsfs to fail

### ISSUE THREAD

**Issue by toby-coleman** [intake/filesystem_spec#598]
When fsspec 0.9.0 is installed I cannot use gcsfs to access GCP storage.

```python
import fsspec
import gcsfs

token = ... # My GCP service account key
project_name = 'my-project'

gcs = gcsfs.GCSFileSystem(token=token, project=project_name)
```

Fails with:
```
Exception ignored in: <function ClientSession.__del__ at 0x7f407d66f830>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/client.py", line 326, in __del__
    if not self.closed:
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/client.py", line 963, in closed
    return self._connector is None or self._connector.closed
AttributeError: 'ClientSession' object has no attribute '_connector'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-7bb3e46172a5> in <module>()
----> 1 gcs = gcsfs.GCSFileSystem(token=token, project=project_name)
```

Downgrading to `fsspec==0.8.7` resolves the problem.

Environment:
python 3.7
gcsfs 0.7.2
fsspec 0.9.0

**Comment by martindurant** [comment]
Please try on main - a release is imminent

**Comment by toby-coleman** [comment]
I still get the issue if I install from main using `pip install -q git+https://github.com/intake/filesystem_spec.git`

**Comment by martindurant** [comment]
Sorry - fsspec is released on pypi, but gcsfs is not yet. Please try 
```
> pip install  git+https://github.com/dask/gcsfs.git
```

**Comment by toby-coleman** [comment]
Yes - that fixes it.

**Comment by jakirkham** [comment]
It looks like the version requirement for `gcsfs` wasn't bumped. Though running with an older `gcsfs` results in errors. Should the `gcsfs` requirement be updated?

https://github.com/intake/filesystem_spec/blob/bb7c23305ce76cb22cd10305f87a49009f363a11/setup.py#L43
https://github.com/intake/filesystem_spec/blob/bb7c23305ce76cb22cd10305f87a49009f363a11/setup.py#L46

cc @kkraus14 @galipremsagar

**Comment by martindurant** [comment]
See https://github.com/dask/gcsfs/pull/371 . Do you mean that the version in the setup.py here should be specified?

**Comment by jakirkham** [comment]
Yeah

**Comment by jakirkham** [comment]
Also I think we need to fix the conda-forge package to include this requirement ( https://github.com/conda-forge/gcsfs-feedstock/pull/32 )

**Comment by martindurant** [comment]
Yep, you go there before me

**Comment by efiop** [comment]
Looks like this is resolved now and can be closed?
