### ISSUE TITLE
Incomplete HTTP reads with 0.9.0

### ISSUE THREAD

**Issue by d70-t** [intake/filesystem_spec#614]
Since the 0.9.0 release HTTP reads are sometimes returned incompletely (i.e. when reading from github). This issue has already been fixed immediately by 65577a7432c077712f02f5036f2995e76a5ce3ad. Would it be possible to have a fixup release soon?

Thank you very much :+1:

**Comment by martindurant** [comment]
Yes!
I have been waiting for consensus on the discussion in https://github.com/dask/s3fs/pull/462 and https://github.com/dask/s3fs/issues/465 on what we should call the next version.
