### ISSUE TITLE
Consider to handle the timeout=0 as None in asyn.py

### ISSUE THREAD

**Issue by scott-zhou** [intake/filesystem_spec#642]
After upgrade fsspec from 0.8.7 to 2021.5.0, I found my application not able to download from Azure Datalake. I found out the reason is I call fs.get(...) with extra argument timeout=0, which in Azure's API means infinite timeout, and with the new implementation for using asyncio, the timeout=0 not work any more, the equivalent usecase is timeout=None.

I would suggest treating timeout=0 as timeout=None. I think for have 0 second timeout is kind of not make sense at all in an async situation (no waiting also means you can't finish anything), and on the other hand, use 0 second timeout to indicate infinite waiting is quite natural for me, not sure how the others think.

Thanks!

**Comment by scott-zhou** [comment]
> Sounds reasonable - and easy to implement as a PR if you have the time.
> […](#)
> On May 19, 2021 10:33:12 AM EDT, Scott Zhou ***@***.***> wrote: After upgrade fsspec from 0.8.7 to 2021.5.0, I found my application not able to download from Azure Datalake. I found out the reason is I call fs.get(...) with extra argument timeout=0, which in Azure's API means infinite timeout, and with the new implementation for using asyncio, the timeout=0 not work any more, the equivalent usecase is timeout=None. I would suggest treating timeout=0 as timeout=None. I think for have 0 second timeout is kind of not make sense at all in an async situation (no waiting also means you can't finish anything), and on the other hand, use 0 second timeout to indicate infinite waiting is quite natural for me, not sure how the others think. Thanks! -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #642
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

PR created. I have a question that might off-topic: I try to set up the development env by tox (follow the README) but it's failed. Not sure what is the issue, and also I found the README might not all correct, it says `tox -e dev`, but there is actually no dev env defined in tox.ini. However, I've never used tox so not sure if it's I'm using it in the wrong way or it's the README outdated.

**Comment by martindurant** [comment]
The best reference for how to run the tests is actually in the CI; but for all practical purposes you will be fine setting up a local conda environment with pytest. Some tests require docker, some require extra packages, but tests should be efficiently skipped when those are not available.
