### ISSUE TITLE
2021.06.0 regression: support for path-like objects are broken 

### ISSUE THREAD

**Issue by isidentical** [intake/filesystem_spec#666]
Reproducer;
```
import os
import fsspec
from pathlib import Path

fs = fsspec.filesystem("file")

path = Path('/tmp/c.txt')
path.write_text('kitten')

print(fs.exists(path))
print(fs.exists(os.fspath(path)))
```

2021.05.0:
```
True
True
```

master:
```
False
True
```

**Comment by isidentical** [comment]
Since this is a regression, would you mind having a new bugfix release @martindurant?

**Comment by martindurant** [comment]
Yes, I will shortly.

**Comment by isidentical** [comment]
Thanks!

**Comment by efiop** [comment]
@martindurant Would it be possible to create a new release, please? We are slightly blocked right now in dvc by it (we could introduce a temporary hack though, if there are problems with creating a new release).

**Comment by martindurant** [comment]
done

**Comment by efiop** [comment]
@martindurant Thank you! :pray:
