### ISSUE TITLE
[IDEA] Implement progress callbacks

### ISSUE THREAD

**Issue by isidentical** [intake/filesystem_spec#668]
It is a very good aspect of the UI to deliver users with updates regarding the process, if the operation is something that takes a while. There are certain operations in fsspec that are like blackboxes. You don't know anything until those are completed. I'd propose we add a callback system for certain APIs, so that client code can show progress bars, take action depending on those etc. etc. 

Here is the list of APIs that might be helpful with progress bars;
- `get_file`/`put_file` => A progress bar showing the full size of the remote file, and the current download/update status. 
- `get`/`put`/`cat` => Total number of files that are going to be transferred, and the current cursor (like `2 of 16 files are transffered`)

There are also possibilities for other APIs (e.g `ls`/`find`) to implement such callbacks, if they take a long time. 

Callbacks are totally optional, and no file system is expected to implement all of them for their all APIs. Also the callback system should be abstracted to level where they are totally separate from the actual logic in the client code. 

Here is the implementation that I've drafted (though I know it is a huge change, so it can drastically evolve): https://github.com/intake/filesystem_spec/compare/master...isidentical:progress?expand=1

Comments would be appreciated.

**Comment by isidentical** [comment]
CC: @martindurant @hayesgb @TomAugspurger @efiop

**Comment by ian-wazowski** [comment]
Good starting point.

**Comment by martindurant** [comment]
I agree that the idea is very attractive. This would involve changing the call signature of get/put/cat/pipe and their _file equivalents to take the extra argument. Some already take kwargs, meaning they may ignore it unless updated, or pass it on to the lower-level library, causing failure. An example of this is AbstractFileSystem.put_file, which passes kwargs on to open().

I am saying that this will need to be implemented carefully and likely need (small) changes in most implementations, including external repos.

Note that for some implementations it really doesn't make that much sense to give per-block feedback, such as libarchive and local caches.

**Comment by isidentical** [comment]
I'd volunteer to add these callbacks (after the fsspec release) to the s3fs/gcsfs/adlfs. Regarding the signature difference, I thought about it before implementing it, and decided that it would make sense to just keep these as hidden options right now and make them part of the official spec when all the major implementations are ready for the change. Since fsspec maintains a db of all registered implementations, we could just go and open an issue on all of them to let them know these APIs are going to change in the future releases.

**Comment by martindurant** [comment]
> Since fsspec maintains a db of all registered implementations

Well, we maintain those that asked to be listed, but maybe that's enough. We do also support entry points and dynamic implementation registration.

> keep these as hidden options right now

How would you call them, then? You would only be using those implementations that you know has this argument? But yes, I see your point that you can add the optional kwarg=None to the various backends first, before changing the spec signature.

**Comment by martindurant** [comment]
Also, when this is finally done, it would be nice to be able to optionally configure a global callback mechanism, so that you can define it once, and then have consistent feedback for all operations.

**Comment by isidentical** [comment]
> Well, we maintain those that asked to be listed, but maybe that's enough. We do also support entry points and dynamic implementation registration.

You are right on this, though being a bit practical, what are the chances of us breaking something major if it is not even listed (or if we aren't even aware such an implementation exists in the first place). If you see the callbacks.branch logic, it tries to be extra careful with not passing `callback=...` to get()/put() if it fallbacks to the default one. So only the downstream will pass these new arguments, and they would probably check all of the filesystems they support before doing so. So I'd say there won't be any breakage at all, but just in time we can create the assumption of these will be migrating to the offical spec and if you can, you should support them (totally optional as documented, since there might be providers that lack of progress/callback system internally, and no need to force for such functionality).


> How would you call them, then? You would only be using those implementations that you know has this argument? But yes, I see your point that you can add the optional kwarg=None to the various backends first, before changing the spec signature

For example the recent `.find(prefix=...)` is only available in specific backends, which it is in the downstream's responsiblity to whether pass that or not since some other implementions might pass all find() kwargs into ls(), which might fail or completely alter the behavior.

**Comment by isidentical** [comment]
> Also, when this is finally done, it would be nice to be able to optionally configure a global callback mechanism, so that you can define it once, and then have consistent feedback for all operations.

Sure! What kind of API do you have in your mind?

**Comment by martindurant** [comment]
```
def get_file(rpath, lpath, callback=DEFAULT, **kwargs):
    if callback == DEFAULT:
        callback = conf.get("transfer_callback", None)
    ...
```

**Comment by isidentical** [comment]
Ah, OK. We already have the implementation in the `callbacks.as_callback` so it is basically a free-feature (beside documentation).

**Comment by martindurant** [comment]
Ah indeed, your code is more complete than I had realised :)

I can't immediately see, do you cope with the case that size is not known (None), which can happen with HTTP?

I do notice some calls to make_path_posix that probably aren't needed or could even be harmful. That aside, the code looks pretty good, you should make it a PR and let's get more people to weigh in on it.

**Comment by isidentical** [comment]
> I can't immediately see, do you cope with the case that size is not known (None), which can happen with HTTP?

Yes, `set_size` is described as `set_size: Callable[[Optional[int]], None] (optional)`. 

> I do notice some calls to make_path_posix that probably aren't needed or could even be harmful. That aside, the code looks pretty good, you should make it a PR and let's get more people to weigh in on it.

Sure.

**Comment by isidentical** [comment]
Here is an example implementation with sshfs + tqdm: https://github.com/iterative/sshfs/pull/1

**Comment by martindurant** [comment]
Out of interest, what does your sshfs have over `fsspec.implementations.sftp.SFTPFileSystem`?

**Comment by isidentical** [comment]
> Out of interest, what does your sshfs have over fsspec.implementations.sftp.SFTPFileSystem?

There are multiple differences, though the primary one is the backend (asyncssh). Also it supports stuff like `copy()`/`checksum()` which aren't available on the SFTP protocol, so it is a mix of SSH+SFTP.

**Comment by martindurant** [comment]
Can I put it the other way then: is there a good reason to keep fsspec's version around? :)

I wonder, do you happen to have an async ftp too? Any others?

**Comment by isidentical** [comment]
> Can I put it the other way then: is there a good reason to keep fsspec's version around? :)

I can't think any. 

> I wonder, do you happen to have an async ftp too? Any others?

There seem to be some [libraries](https://github.com/aio-libs/aioftp).

**Comment by efiop** [comment]
There are a few considerations about it though. Since paramiko has been around for a such a long time, there is a possibility that some edge cases that we didn't catch yet are better handled there than in asyncssh. @isidentical Please correct me if I'm wrong, but another thing is that currently sshfs only provides an ssh filesystem, while fsspecs is pure sftp and for some use cases that might make sshfs not work. Though this one is solvable by sshfs providing both SSHFileSystem and SFTPFileSystem.

**Comment by isidentical** [comment]
> Please correct me if I'm wrong, but another thing is that currently sshfs only provides an ssh filesystem, while fsspecs is pure sftp and for some use cases that might make sshfs not work

Though all operations currently supported is already using SFTP under the hood in sshfs, so there wouldn't be any breakage on that front. Only the new methods (`cp_file`/`checksum`, and in some rare cases `move()` [but those would result with an error in the existing SFTPFileSystem]) does command execution.
