### ISSUE TITLE
`open_local` does not keep original extension

### ISSUE THREAD

**Issue by AndreiBarsan** [intake/filesystem_spec#669]
I am trying to use fsspec with caching to expand S3 to some Python libraries which only take local paths, such as Open3D's IO.

To this end, I'm trying to use a file cache like this:
```python
my_local_path = fsspec.open_local(f"simplecache::{remote_uri}", filecache={"cache_storage": "/tmp/my_cache"})
some_downstream_code_that_does_not_like_file_handles_and_buffers(my_local_path)
```

This seems to work, but generates a dynamic file name, which no longer has the extension of the original file. It looks like:
`'/tmp/tmph1czm30t/726f7adfb2039c45dd938126377d6838e26334e25069df896806c718f0ab3818'`

This causes downstream libraries which I do not control complain about an incorrect extension.

The current solution to this is to manually copy the remote file locally to a tmp file name with the right extension, and passing that to my downstream code. However, I would prefer to avoid this hack and just rely on the nice caching support fsspec already has.

**Comment by martindurant** [comment]
`simplecache` takes the argument `same_names=`, which you will want here. Note that it comes with the risk that files with the same names from different URLs/backends will clash.

```
my_local_path = fsspec.open_local(
    f"simplecache::{remote_uri}",
    simplecache={"cache_storage": "/tmp/my_cache", "same_names": True}
)
```

**Comment by AndreiBarsan** [comment]
Speedy and super helpful response as always! Thank you Martin, I had missed that part of the API, this works perfectly! (I was looking at `filecache`; note my buggy code which tried simplecache in the URI but was passing options to filecache.)
