### ISSUE TITLE
Support compound URLs

### ISSUE THREAD

**Issue by martindurant** [intake/filesystem_spec#67]
With the cached FS and dask worker FS, not to mention zip, we have file-systems which take as input other file-systems or URLs. It would be convenient, but potentially confusing, to be able to address them with a single url:
```
"zip://s3://bucket/file.zip"
```

In practice, it may be tricky to differentiate between the parts of the path belong to which FS. This would probably need more syntax and maybe lead to more confusion than it clears up.

**Comment by ian-r-rose** [comment]
For what it's worth, [`fiona`](https://fiona.readthedocs.io/en/latest/README.html#collections-from-archives-and-virtual-file-systems) chooses a somewhat different syntax for compound urls with virtual filesystems:
```
"zip+s3://bucket/file.zip"
```

**Comment by martindurant** [comment]
Agree, but does the above give you one file or all of the files contained in the zip? If you include glob characters (for open_files), is that performed on s3 or in the zip?

**Comment by sgillies** [comment]
Does the existing URL chaining feature resolve this issue or is there something else to compound URLs @martindurant ?

The fiona library used by geopandas does have a different syntax, a syntax that was an attempt to improve on [GDAL's chaining syntax](https://gdal.org/user/virtual_file_systems.html#chaining). I have never enjoyed the idea that all zipfiles on S3 are virtually mounted on my filesystem under `/vsizip/vsis3/`. However, fiona's syntax is only cosmetic. Its Python classes rewrite, for example, `zip+s3://...` URIs to `/vsizip/vsis3/...` before passing them to GDAL functions.

I see fsspec's chaining, especially for longer and more complex chains, as better than shoehorning all the protocols into one URI scheme. Whether parameters in a URL query string apply to the "s3" or the "zip" part of the scheme is undefined. I think you alluded to that above @martindurant. Whereas with fsspec's chaining, something like `zip://bar.shp?key=val::https://example.org/foo.zip?key=val`, a compact string encoding of the protocols and their options, may be feasible.

One thing that GDAL does well, and which I haven't seen yet in fsspec, is providing access to multiple-file data formats zipped together. Like the zipped-up shapefile (actually 3+ files), or a TIFF with georeferencing and other metadata.

**Comment by martindurant** [comment]
Yes, I will close this issue. Happy to continue the conversation here, though.

I must admit that I was wary of making my own syntax, and "mounting" into a current file-system tree certainly has a good pedigree. pyfilesystem2 support this, for instance, not to mention posix.

I think it's still fair to say that fsspec prefers kwargs to formatting arguments/queries into the URL itself, because it's much more flexible.

> providing access to multiple-file data formats zipped together

Not quite sure what you mean. The following does work
```
fsspec.open("zip://*::s3://bucket/file.zip")
```
to create a list of open-files. You can choose to cache the original file or the decompressed files. However, you cannot glob for multiple zip files, since each is seen as a separate file system.

**Comment by mxmlnkn** [comment]
This definitely needs some documentation or did I miss something? The only mention I wsa able to find in the readthedocs was this line `Also accepts compound URLs like zip::s3://bucket/file.zip` and then I searched the Github code for `zip::` and found this test, which fits my intended use case:

https://github.com/fsspec/filesystem_spec/blob/176efbe02179f30b5862bf7444a383b8e62f87df/fsspec/tests/test_api.py#L281-L282

but this is too hidden for the normal user who wants to use this via pandas for example.

**Comment by martindurant** [comment]
Certainly, would love to see improvements to the documentation between ZIP/TAR/libarchive and how they relate to one-another. ZIP can first, and some of its docstrings have moved upstream, but ended up in libarchive. 

From your point of view, the salient thing to know, is that many FSs like these act on either another filesystem (e.g., DirFilesystem) or an open file (TAR). They take conventional arguments `fs=` and `fo=`, respectively, and in some cases `target_protocol`/`target_options` if are asking the filesystem to create a filesystem instance internally.
Chaining populates fs/fo arguments from the rest of the URL and infers arguments. 

> What about files/folders/paths containing :: in their file name?

This unfortunately fails with the top-level functions, but can still be made to work by instantiating the filesystems directly.
