### ISSUE TITLE
API mismatch between mapping and implementations

### ISSUE THREAD

**Issue by d-v-b** [intake/filesystem_spec#677]
the [`delitems`](https://github.com/intake/filesystem_spec/blob/master/fsspec/mapping.py#L113) method in `FSMap` expects the underlying filesystem to have an `rm` method that accepts a list of strings. However, this behavior of `FSMap` appears to be untested, and if tested would certainly fail for at least [`LocalFileSystem.rm`](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/local.py#L124), which accepts only a single string as input. Would a PR changing the behavior of `LocalFileSystem.rm` + adding tests be welcome? This would help move this Zarr PR forward: https://github.com/zarr-developers/zarr-python/pull/738#issuecomment-849966740

**Comment by martindurant** [comment]
> Would a PR changing the behavior of LocalFileSystem.rm + adding tests be welcome? 

Yes please!
