### ISSUE TITLE
`FTPFileSystem.mkdir()` has no support for `create_parents=True`

### ISSUE THREAD

**Issue by matteosantama** [intake/filesystem_spec#702]
The interface in `spec.py` defines the signature for `mkdir` as

```python
def mkdir(self, path, create_parents=True, **kwargs):
    """
    Create directory entry at path
    For systems that don't have true directories, may create an for
    this instance only and not touch the real filesystem
    Parameters
    ----------
    path: str
        location
    create_parents: bool
        if True, this is equivalent to ``makedirs``
    kwargs:
        may be permissions, etc.
    """
    pass  # not necessary to implement, may not have directories
```

The implementation in `implementations/ftp.py` is

```python
def mkdir(self, path, **kwargs):
    path = self._strip_protocol(path)
    self.ftp.mkd(path)
    self.invalidate_cache(self._parent(path))
```

which doesn't make use of the `create_parents` argument.

I propose adding support for this parameter by traversing up the tree and creating the directories as needed.

**Comment by martindurant** [comment]
You found another on! :)

I can get to this eventually, but you might have the time to implement it yourself. Note that the spec also defines `makedirs`, which would have the same effect in most conditions.

**Comment by matteosantama** [comment]
I'm happy to put something together.

I'm following the section on the `README.md`

> fsspec uses tox and tox-conda to manage dev and test environments. First, install conda with tox and tox-conda in a base environment (eg. conda install -c conda-forge tox tox-conda). Calls to tox can then be used to configure a development environment and run tests.
First, setup a development conda environment via tox -e dev. This will install fspec dependencies, test & dev tools, and install fsspec in develop mode. Then, activate the dev environment under .tox/dev via conda activate .tox/dev.

I ran  `conda install -c conda-forge tox tox-conda` in my `base` environment, but now I'm getting

```
$ tox -e dev
ERROR: unknown environment 'dev'
```

Any idea if I'm missing something?

**Comment by martindurant** [comment]
Sorry, the environments got renamed at some point. You can choose from {py36,py37,py38,py39}. For FTP, you don't actually need much, probably only pyftplib.

**Comment by matteosantama** [comment]
Ok, great. I will update that section of the README too
