### ISSUE TITLE
`FTPFileSystem` does not properly handle directories in `.rm(recursive=True)`

### ISSUE THREAD

**Issue by matteosantama** [intake/filesystem_spec#708]
Sorry @martindurant, another `FTPFileSystem` problem I've come across.

I am trying to delete a populated ftp directory. Using `rmdir()` complains about trying to delete a non-empty directory. When I try `rm(..., recursive=True)`, I get an `ftplib.error_perm: 550 Operation not permitted`.

It comes down to this,

### spec.py

```python
def rm_file(self, path):
    """Delete a file"""
    self._rm(path)

def _rm(self, path):
    """Delete one file"""
    # this is the old name for the method, prefer rm_file
    raise NotImplementedError

def rm(self, path, recursive=False, maxdepth=None):
    """Delete files.
    Parameters
    ----------
    path: str or list of str
        File(s) to delete.
    recursive: bool
        If file(s) are directories, recursively delete contents and then
        also remove the directory
    maxdepth: int or None
        Depth to pass to walk for finding files to delete, if recursive.
        If None, there will be no limit and infinite recursion may be
        possible.
    """
    path = self.expand_path(path, recursive=recursive, maxdepth=maxdepth)
    for p in reversed(path):
        self.rm_file(p)
```

### ftp.py
```python
def _rm(self, path):
    path = self._strip_protocol(path)
    self.ftp.delete(path)
    self.invalidate_cache(self._parent(path))
```

but it seems `ftp.delete` is not the right call for a directory, it should instead be `ftp.rmd`.

`rm(..., recursive=True)` actually does remove all the files before throwing the error, so I am able to work around it by doing something like

```python
try:
    fs.rm(directory, recursive=True)
except ftplib.error_perm:
    fs.rmdir(directory)
```

**Comment by matteosantama** [comment]
If that's the intended behavior, feel free to close this issue.

**Comment by martindurant** [comment]
I am coming around to fixing this soon. You are right that `rm(recursive=True)` on a directory should remove the directory too.
