### ISSUE TITLE
Filesystem put fails if inputs and outputs are lists of individual files

### ISSUE THREAD

**Issue by baxen** [intake/filesystem_spec#712]
As of 2021.7.0, any put operations that use lists of files raise an assertion error. 

I believe this is a general issue with fsspec asyn, but have tested this with GCS. 

```
In [1]:  import fsspec

In [2]: fs = fsspec.get_filesystem_class('gs')()

In [3]: !tree .
.
├── e1.txt
└── e2.txt

0 directories, 2 files

In [4]: fs.put(['e1.txt', 'e2.txt'], ['gs://redacted/e1.txt', 'gs://redacted/e2.txt'], recursive=False)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
....
~/.pyenv/versions/3.7.4/envs/blocks/lib/python3.7/site-packages/fsspec/asyn.py in _put(self, lpath, rpath, recursive, callback, **kwargs)
    380         lpaths = fs.expand_path(lpath, recursive=recursive)
    381         dirs = [l for l in lpaths if os.path.isdir(l)]
--> 382         rdirs = other_paths(dirs, rpath)
    383         await asyncio.gather(*[self._makedirs(d, exist_ok=True) for d in rdirs])
    384         files = sorted(set(lpaths) - set(dirs))

~/.pyenv/versions/3.7.4/envs/blocks/lib/python3.7/site-packages/fsspec/utils.py in other_paths(paths, path2, is_dir)
    366                 path2 = [path2]
    367     else:
--> 368         assert len(paths) == len(path2)
    369     return path2
    370

```

I believe this was introduced with this change https://github.com/intake/filesystem_spec/commit/19e57e090324ef7a7a6cb3d039c0f80db15dd714#diff-9e28a72564624d8305a58b77c04c514d15e016b61899fd507b52b30388ef6ab6, since the other_paths is asserting equal length lists but the directories filter empties the source list. 

It looks like the intent of that function is to support the input list being any combination of directories and files, and the change just happened to break the case where rpaths is a list (which needs a slightly more complicated implementation)? If that's correct I can submit a fix.

**Comment by martindurant** [comment]
Your analysis sounds right

On July 19, 2021 5:26:57 PM EDT, Bradley Axen ***@***.***> wrote:
>As of 2021.7.0, any put operations that use files (rather than
>directories) raise an assertion error. >
>>
>I believe this is a general issue with fsspec, but have tested this
>with GCS. >
>>
>```>
>In [1]:  import fsspec>
>>
>In [2]: fs = fsspec.get_filesystem_class('gs')()>
>>
>In [3]: !tree .>
>.>
>├── e1.txt>
>└── e2.txt>
>>
>0 directories, 2 files>
>>
>In [4]: fs.put(['e1.txt', 'e2.txt'], ['gs://redacted/e1.txt',
>'gs://redacted/e2.txt'], recursive=False)>
>--------------------------------------------------------------------------->
>AssertionError                            Traceback (most recent call
>last)>
>....>
>~/.pyenv/versions/3.7.4/envs/blocks/lib/python3.7/site-packages/fsspec/asyn.py
>in _put(self, lpath, rpath, recursive, callback, **kwargs)>
>    380         lpaths = fs.expand_path(lpath, recursive=recursive)>
>    381         dirs = [l for l in lpaths if os.path.isdir(l)]>
>--> 382         rdirs = other_paths(dirs, rpath)>
>383         await asyncio.gather(*[self._makedirs(d, exist_ok=True) for
>d in rdirs])>
>    384         files = sorted(set(lpaths) - set(dirs))>
>>
>~/.pyenv/versions/3.7.4/envs/blocks/lib/python3.7/site-packages/fsspec/utils.py
>in other_paths(paths, path2, is_dir)>
>    366                 path2 = [path2]>
>    367     else:>
>--> 368         assert len(paths) == len(path2)>
>    369     return path2>
>    370>
>>
>```>
>>
>I believe this was introduced with this change
>https://github.com/intake/filesystem_spec/commit/19e57e090324ef7a7a6cb3d039c0f80db15dd714#diff-9e28a72564624d8305a58b77c04c514d15e016b61899fd507b52b30388ef6ab6,
>since the other_paths is asserting equal length lists but the
>directories filter empties the source list. >
>>
>It looks like the intent of that function is to support the input list
>being any combination of directories and files, and the change just
>happened to break the case where rpaths is a list (which needs a
>slightly more complicated implementation)? If that's correct I can
>submit a fix. >
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/intake/filesystem_spec/issues/712

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
