### ISSUE TITLE
LocalFileSystem implement rm, not _rm

### ISSUE THREAD

**Issue by chrisroat** [intake/filesystem_spec#730]
`AbstractFileSystem` implements `rm` and `rm_file`, which both end up calling `_rm`.  `LocalFileSystem` does not implement `_rm` (but does override `rm`), and its call to `rm_file` fails.

What is the right way forward here?  I think it's an easy change to make things consistent, but a decision needs to be made.  Should `LocalFileSystem` be implementing `_rm`, or should the `AbstractFileSystem` implementing `rm_file` to call `rm` and get rid of `_rm`?

**Comment by martindurant** [comment]
LocalFileSystem should probably have an `rm_file`. The reason for the difference, is that locally, you can call `shutil.rmtree`, whereas for most/all other implementations, you need to explicitly find all the files and folders to remove first, and then remove them.
Whether the method is called `_rm` or `rm_file` in the base class is not important, I see it just as an alias (like `delete`, which also exists!). The former exists for backward compatibility, and the latter fits better with the style elsewhere.

**Comment by chrisroat** [comment]
Gotcha.  I will put together a PR.

You've piqued my interest about the other implementations.  For example, do you know how the performance of a recursive delete using `gcsfs` compares to `gsutil -m rm -r` (where `-r` does recursive delete and `-m` causes parallel operations)?
