### ISSUE TITLE
Regression: LocalFileSystem now tries to resolve links

### ISSUE THREAD

**Issue by isidentical** [intake/filesystem_spec#742]
<details>
<summary> Test Script </summary>

```py
import contextlib
import os

import fsspec

def cleanup(*files):
    for file in files:
        with contextlib.suppress(FileNotFoundError):
            os.unlink(file)

cleanup("/tmp/test", "/tmp/link")


# Create a file, symlink it to another path and
# delete the original
with open("/tmp/test", "w") as stream:
    stream.write("hey")
os.symlink("/tmp/test", "/tmp/link")
os.unlink("/tmp/test")

fs = fsspec.filesystem("file")

print("(fsspec) /tmp/test exists:", fs.exists("/tmp/test"))
print("(fsspec) /tmp/link exists:", fs.exists("/tmp/link"))

print("(os) /tmp/test exists:", os.path.exists("/tmp/test"))
print("(os) /tmp/link exists:", os.path.exists("/tmp/link"))
```

</details>

With the script above, `fsspec==2021.07.0` returns `True` for `fs.exists()` on a symlink where the original file it is linked to is deleted. After https://github.com/intake/filesystem_spec/commit/63a668fb4a60d41efc66c5f6445b6a500d5e4396, it now returns `False` since it tries to resolve the links via `follow_links=True`. 

I personally find the change to make sense, considering this is how the `os.path.exists` behaves but I believe it should be explicitly mentioned in the changelog and as well as an option to opt-out from it. Perhaps a keyword option called `follow_symlinks=...` to the `info` and `exists` or a method called `lexists()` (similiar to [os.path.lexists](https://docs.python.org/3/library/os.path.html#os.path.lexists)).

**Comment by martindurant** [comment]
Would be happy to see `lexists` added. I suppose it would only make any sense for local and maybe ssh.

**Comment by martindurant** [comment]
Is that an OK plan? Should we close this?

**Comment by isidentical** [comment]
The issue is not resolved yet, so I don't think we should close it. I'll try to come up with a patch
