### ISSUE TITLE
Make url_to_fs public

### ISSUE THREAD

**Issue by TomAugspurger** [intake/filesystem_spec#752]
url_to_fs is used in pandas, and geopandas would like to [use it too](https://github.com/geopandas/geopandas/pull/2107/files#r707166346) but it isn't documented in the public API. Any objections to adding it to the public API?

Is `fsspec.core.*` considered public and it just needs to be documented?

**Comment by martindurant** [comment]
Originally, I think only identifiers exported to the package root would be considered public, but I think that has shifted over time. So yes to documenting things in core, or it could be imported in init, or both.
