### ISSUE TITLE
RuntimeError: This class is not fork-safe

### ISSUE THREAD

**Issue by datNurd** [intake/filesystem_spec#755]
I am trying to use Fspec via S3fs inside my Python celery project to upload and download files from S3 bucket. However I am getting "RuntimeError: This class is not fork-safe" when I call the fs.open() command. Let me know how this can be solved. I am using windows 10 WSL 1 ubuntu.

**Comment by martindurant** [comment]
You should set your multiprocessing context to use spawn or forkserver: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method

**Comment by datNurd** [comment]
Hi @martindurant, Thank you for your prompt response. I figured that I was initializing the file system and calling the open method in two different tasks which is causing this issue. I have fixed the same and its working as expected.
