### ISSUE TITLE
What FUSE library does `filesystem_spec` use?

### ISSUE THREAD

**Issue by jwodder** [intake/filesystem_spec#768]
[The docs for this library currently state](https://filesystem-spec.readthedocs.io/en/latest/features.html#mount-anything-with-fuse):

> Any path of any file-system can be mapped to a local directory using pyfuse and `fsspec.fuse.run()`.

However, there is no library called "pyfuse" on PyPI.  There's a [pyfuse3](https://pypi.org/project/pyfuse3/), but it uses the module name "pyfuse3", whereas [`filesystem_spec` imports "fuse"](https://github.com/intake/filesystem_spec/blob/b0ce4015481cea0d68fa45db8d53fd511d7b0922/fsspec/fuse.py#L8).  The FUSE libraries that I can find that name their module "fuse" are [fuse-python](https://pypi.org/project/fuse-python/) and [fusepy](https://pypi.org/project/fusepy/).  I suspect that `filesystem_fuse` intends to use fusepy, as it is the only one of the two that provides classes named `FuseOSError` and `Operations`.  `filesystem_spec` should make it clear what fuse library it uses by updating the docs and, preferrably, by adding the library as a (possibly extra) dependency.

Side note: I see in the source for [`docs/source/api.rst`](https://github.com/intake/filesystem_spec/blob/master/docs/source/api.rst) the line `.. autofunction:: fsspec.fuse.run`, but the documentation for this function does not appear in [the Readthedocs site](https://filesystem-spec.readthedocs.io/en/latest/api.html).

**Comment by martindurant** [comment]
Yes, it should be documented indeed, and the docstring fixed too. Do you think you have the time to contribute? Yes, it is fusepy; but we don't want to make it a dependency (fsspec has no deps, and fuse is not much used), but it could be in `extras_require`.
