### ISSUE TITLE
FSSpec 2021.9.0 Introduces Breaking Changes to the HDFS Api

### ISSUE THREAD

**Issue by j3doucet** [intake/filesystem_spec#777]
it looks like one or more PRs merged as part of the 2021.9.0 release cause breaking changes in how FSSpec is used to access HDFS.

The breaking behaviors we observe are:

- Calling `get("hdfs://CLUSTER/a/b/c.txt", "local.txt")` would previously copy the contents of `/a/b/c.txt` on CLUSTER to the local file `local.txt`. Now it tries to copy it to `local.txt/a/b/c.txt`, which does not exist, causing a `FileNotFoundError`.

- Calling `copy("hdfs://CLUSTER/a/somedir/", "somelocaldir", recursive=True)` would previously recursively copy the contents of remote path `/a/somedir/` to the local directory `somelocaldir`. Now it fails with `pyarrow.lib.ArrowInvalid`. 

Some example code snippets that reproduce this behavior (paths anonymized):

With fsspec==2021.9.0:
```python
import fsspec

my_fs = fsspec.filesystem('hdfs')
my_fs.get("hdfs://CLUSTER/a/b/c.txt", "local.txt", recursive=True)
>> FileNotFoundError: [Errno 2] No such file or directory: '/user/home/local.txt/a/b/c.txt'
```

With fsspec==2021.9.0:
```python
import pandas as pd
pd.read_parquet("hdfs://CLUSTER/dir")  # read_parquet wraps pyarrow, which wraps fsspec
>> ArrowInvalid: GetFileInfo() yielded path 'hdfs://CLUSTER/dir/dir.snappy.parquet', which is outside base dir '/dir'
```

Whereas, with fspec==2021.8.1 both examples execute correctly.

Our guess is that the offending change may be https://github.com/isidentical/filesystem_spec/blob/88bc8f1ff1737e9e83cdb7b8aabae3ed331b6bcf/fsspec/implementations/hdfs.py#L181.

This appears to affect all users of `pandas` who use `read_parquet` with partitioned datafiles, so it could be a big impact. Suggest reverting #749 .

**Comment by j3doucet** [comment]
> @isidentical
> 
> Question to @j3doucet : what form does CLUSTER take for you?

Cluster is the name of an HDFS storage cluster we use internally.

**Comment by isidentical** [comment]
Can you share the full tracebacks @j3doucet? (including all the frames, so we can see where the exception is getting raised at)

**Comment by martindurant** [comment]
Is is a single string, domain name (qualified or not), an IP address, or something else? Do you encode user credentials into the URL?

**Comment by j3doucet** [comment]
For the `read_parquet` example, my traceback looks like:

```python
~/.local/lib/python3.7/site-packages/pandas/io/parquet.py in read_parquet(path, engine, columns, storage_options, use_nullable_dtypes, **kwargs)
    498         storage_options=storage_options,
    499         use_nullable_dtypes=use_nullable_dtypes,
--> 500         **kwargs,
    501     )

~/.local/lib/python3.7/site-packages/pandas/io/parquet.py in read(self, path, columns, use_nullable_dtypes, storage_options, **kwargs)
    238         try:
    239             result = self.api.parquet.read_table(
--> 240                 path_or_handle, columns=columns, **kwargs
    241             ).to_pandas(**to_pandas_kwargs)
    242             if manager == "array":

~/.local/lib/python3.7/site-packages/pyarrow/parquet.py in read_table(source, columns, use_threads, metadata, use_pandas_metadata, memory_map, read_dictionary, filesystem, filters, buffer_size, partitioning, use_legacy_dataset, ignore_prefixes)
   1613                 buffer_size=buffer_size,
   1614                 filters=filters,
-> 1615                 ignore_prefixes=ignore_prefixes,
   1616             )
   1617         except ImportError:

~/.local/lib/python3.7/site-packages/pyarrow/parquet.py in __init__(self, path_or_paths, filesystem, filters, partitioning, read_dictionary, buffer_size, memory_map, ignore_prefixes, **kwargs)
   1468                                    format=parquet_format,
   1469                                    partitioning=partitioning,
-> 1470                                    ignore_prefixes=ignore_prefixes)
   1471 
   1472     @property

~/.local/lib/python3.7/site-packages/pyarrow/dataset.py in dataset(source, schema, format, filesystem, partitioning, partition_base_dir, exclude_invalid_files, ignore_prefixes)
    669     # TODO(kszucs): support InMemoryDataset for a table input
    670     if _is_path_like(source):
--> 671         return _filesystem_dataset(source, **kwargs)
    672     elif isinstance(source, (tuple, list)):
    673         if all(_is_path_like(elem) for elem in source):

~/.local/lib/python3.7/site-packages/pyarrow/dataset.py in _filesystem_dataset(source, schema, filesystem, partitioning, format, partition_base_dir, exclude_invalid_files, selector_ignore_prefixes)
    434         selector_ignore_prefixes=selector_ignore_prefixes
    435     )
--> 436     factory = FileSystemDatasetFactory(fs, paths_or_selector, format, options)
    437 
    438     return factory.finish(schema)

~/.local/lib/python3.7/site-packages/pyarrow/_dataset.pyx in pyarrow._dataset.FileSystemDatasetFactory.__init__()

~/.local/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.pyarrow_internal_check_status()

~/.local/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()
```

**Comment by j3doucet** [comment]
For the `fsspec.filesystem.get` example, by traceback looks like:

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-46c9264b8e93> in <module>
      1 import fsspec
      2 my_fs = fsspec.filesystem('hdfs')
----> 3 my_fs.get("hdfs://CLUSTER/redacted_remote_path/", "redacted_local_filename", recursive=True)

~/.local/lib/python3.7/site-packages/fsspec/spec.py in get(self, rpath, lpath, recursive, callback, **kwargs)
    791         for lpath, rpath in callback.wrap(zip(lpaths, rpaths)):
    792             callback.branch(rpath, lpath, kwargs)
--> 793             self.get_file(rpath, lpath, **kwargs)
    794 
    795     def put_file(self, lpath, rpath, callback=_DEFAULT_CALLBACK, **kwargs):

~/.local/lib/python3.7/site-packages/fsspec/spec.py in get_file(self, rpath, lpath, callback, **kwargs)
    764         with self.open(rpath, "rb", **kwargs) as f1:
    765             callback.set_size(getattr(f1, "size", None))
--> 766             with open(lpath, "wb") as f2:
    767                 data = True
    768                 while data:

FileNotFoundError: [Errno 2] No such file or directory: '/home/username/redacted_local_filename/redacted_remote_path'
```

**Comment by isidentical** [comment]
Still debugging (and probably send a fix tonight) though my first impression is that something is wrong with expand_paths/strip_protocol (probably due to new inheriting system / overrides etc)

**Comment by jaedoucette** [comment]
> Still debugging (and probably send a fix tonight) though my first impression is that something is wrong with expand_paths/strip_protocol (probably due to new inheriting system / overrides etc)

Agreed. We narrowed this down a bit in our own testing.

It looks like part of this change is that previously, if you passed `recursive=True` to `get`, along with a remote path that resolved to a single file and a local path that resolved to a single file, then it effectively ignored `recursive=True`. Now, it tries to copy the remote file into a subdirectory under the local file.

Additionally, in 2021.8.1 if you pass a remote path that resolved to a directly and a local path that resolved to a directory, and `recursive=True`, the contents of the remote path were copied into the same relative locations under the local path. Now, it looks like it tries to copy the contents of the remote path to `local_path/fully/specified/remote/path`.

This change might also be at the root of the changed Pandas behavior, though that's harder to verify.

**Comment by isidentical** [comment]
@martindurant would it make sense to currently yank (https://pypi.org/help/#yanked) 9.0 of fsspec/s3fs/gcsfs until we solve these issues? I was on vacation for the last 3 days, but am going to be back starting from tonight. Can take care of these bugs and then we can bump a stable 9.1 release.

**Comment by isidentical** [comment]
Probably I should be able to send all today, though we might need to work
on the testing infrastructure since I think we don't test hdfs on CI.

**Comment by martindurant** [comment]
OK, then we can wait, I think.

**Comment by isidentical** [comment]
> Calling copy("hdfs://CLUSTER/a/somedir/", "somelocaldir", recursive=True) would previously recursively copy the contents of remote path /a/somedir/ to the local directory somelocaldir. Now it fails with pyarrow.lib.ArrowInvalid.

@j3doucet just to verify, from what I can tell previously copying didn't work on in `PyArrowHDFS`. A `copy()` call or `cp_file()` call is just raising `NotImplementedError` on the 2021.08.01. How did you used to copy?

**Comment by jaedoucette** [comment]
@isidentical 

Apologies, by copy I meant `get`, as shown in the example code in my initial comment. 

With 2021.8.1, using `get` to copy a remote directory to a local destination would place the _contents_ of the remote directory into the local location, rooted at that location. For example, suppose I have the remote directory layout:

-> a
     | -> b
            | -> c
            |       | -> d.txt
            | -> e.txt

and call

`get("hdfs://CLUSTER/a/b/", "local_dir", recursive=True)` 

With 2021.8.1 installed, I get a local directory layout that looks like:

local_dir
            | -> c
            |       | -> d.txt
            | -> e.txt
            
Which is the behavior I expect.

Running the same command in 2021.9.0 does something very different. It creates the following local directory layout:

local_dirhdfs:/ [sic]
            | ->CLUSTER
                          | -> a
                                 | -> b
                                         | -> c
                                         |       | -> d.txt
                                         | -> e.txt
local_dir
          | -> a
                  | -> b
                          | -> c
                          |       | -> d.txt
                          | -> e.txt
            
That is, it creates not just one, but two copies of the remote directory's contents, and it also copies the absolute path of the remote directory into my local directory, rather than just the contents.
