### ISSUE TITLE
glob doesn't pass extra parameters to ls

### ISSUE THREAD

**Issue by ophiry** [intake/filesystem_spec#89]
according to this: https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L420 glob should pass extra kwargs to the ls function.

I tried using the details=True flag, but got an exception

```
import fsspec
fs = fsspec.get_filesystem_class('s3')()
fs.glob('s3://bucket/*', detail=True)

```
```
  File "fsspec_test.py", line 3, in <module>
    fs.glob('s3://bucket/*', detail=True)
  File "./lib/python3.7/site-packages/fsspec/spec.py", line 444, in glob
    allpaths = self.find(root, maxdepth=depth, **kwargs)
  File "./lib/python3.7/site-packages/fsspec/spec.py", line 373, in find
    for path, _, files in self.walk(path, maxdepth, **kwargs):
TypeError: walk() got an unexpected keyword argument 'detail'

```

**Comment by martindurant** [comment]
The implementation of [`walk`](https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L310) does indeed allow kwargs, but maybe you need to be using the master version.

**Comment by ophiry** [comment]
master version didn't help.
tried debugging a bit, it appears that the issue is that while AbstractFileSystem.walk() allows kwargs, the S3Filesystem.walk() doesn't

**Comment by martindurant** [comment]
Ah, the fix is in https://github.com/dask/s3fs/pull/210 , which got stalled because of upstream release of botocore causing errors. Coming soon!
