### ISSUE TITLE
Question about glob implementation

### ISSUE THREAD

**Issue by jcrist** [intake/filesystem_spec#95]
Currently the default implementation of glob is handwritten for this package, and relies on `find` and some custom regexes (which have given problems in [the](https://github.com/intake/filesystem_spec/issues/36) [past](https://github.com/intake/filesystem_spec/issues/58)/[currently](#94)). An alternative implementation may be similar to what we [used to have in dask](https://github.com/dask/dask/blob/ed33fbe6ec47e361d1f6f45b84acfe0a98e511ca/dask/bytes/glob.py#L60-L139). This is based on the implementation in CPython, passes all their tests, and relies on the following standard filesystem methods:

- ls
- isdir
- exists

Is there a reason to prefer the implementation in this repo over the one generalized from CPython we used to have in dask? Would it be worth investigating using the other version?

**Comment by martindurant** [comment]
If memory serves, that version does not implement ** and does not escape regex characters correctly. May we worth another look.

**Comment by rsignell-usgs** [comment]
Are there any examples of how glob currently works?   
Clearly this doesn't.:
```python
import fsspec
fs = fsspec.filesystem('s3', anon=True)
fs.ls('prd-tnm/StagedProducts/Elevation/1/TIFF')
fs.ls('prd-tnm/StagedProducts/Elevation/1/TIFF/n06*')
```

**Comment by martindurant** [comment]
You need to actually call `fs.glob`, `ls` does not evaluate wildcards.

**Comment by rsignell-usgs** [comment]
Oh, duh:
```python
fs.glob('prd-tnm/StagedProducts/Elevation/1/TIFF/n06*')
```

**Comment by martindurant** [comment]
```
In [8]: s3.glob('prd-tnm/StagedProducts/Elevation/1/TIFF/n06*')
Out[8]:
['prd-tnm/StagedProducts/Elevation/1/TIFF/n06e162',
 'prd-tnm/StagedProducts/Elevation/1/TIFF/n06e163']
```

OK?

**Comment by d-v-b** [comment]
for some reason this hangs:
`s3.glob('janelia-cosem/*')` 
while the equivalent `s3.ls()` command finishes essentially instantly. Any idea what's going on?

**Comment by martindurant** [comment]
Would you mind trying with fsspec master and s3fs master? I believe this is fixed and may have to do with the exact version combination you have.

**Comment by rsignell-usgs** [comment]
![2020-11-10_10-10-19](https://user-images.githubusercontent.com/1872600/98692335-ffb51700-233c-11eb-94b7-ef7fdb317b0a.png)

**Comment by d-v-b** [comment]
master is working as expected for me, thanks for the tip!

**Comment by martindurant** [comment]
I'll put a set of releases on my to-do
